package adminapi

import (
	"encoding/json"
	"net/http"
	"net/http/httptest"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

func TestHandleGetOpenAPI(t *testing.T) {
	_ = prepareSupportBundleTestConfig(t)

	req := httptest.NewRequest(http.MethodGet, "https://appliance.example.test/api/v1/openapi.json", nil)
	rec := httptest.NewRecorder()

	HandleGetOpenAPI(rec, req)

	require.Equal(t, http.StatusOK, rec.Code)
	assert.Equal(t, "application/json", rec.Header().Get("Content-Type"))

	var payload map[string]any
	require.NoError(t, json.Unmarshal(rec.Body.Bytes(), &payload))

	assert.Equal(t, "3.1.0", payload["openapi"])

	info, ok := payload["info"].(map[string]any)
	require.True(t, ok)
	assert.Equal(t, "AegisNAS Admin API", info["title"])

	paths, ok := payload["paths"].(map[string]any)
	require.True(t, ok)

	statusPath, ok := paths["/api/v1/system/status"].(map[string]any)
	require.True(t, ok)
	statusGet, ok := statusPath["get"].(map[string]any)
	require.True(t, ok)
	assert.Equal(t, "Read system runtime status", statusGet["summary"])
	assert.Contains(t, statusGet["x-aegisnas-roles"], "read_only")

	vendorCompatibilityPath, ok := paths["/api/v1/system/vendor-compatibility"].(map[string]any)
	require.True(t, ok)
	vendorCompatibilityGet, ok := vendorCompatibilityPath["get"].(map[string]any)
	require.True(t, ok)
	assert.Equal(t, "Read vendor compatibility catalog", vendorCompatibilityGet["summary"])
	assert.Contains(t, vendorCompatibilityGet["x-aegisnas-roles"], "read_only")

	specPath, ok := paths["/api/v1/openapi.json"].(map[string]any)
	require.True(t, ok)
	specGet, ok := specPath["get"].(map[string]any)
	require.True(t, ok)
	assert.Equal(t, "public", specGet["x-aegisnas-visibility"])

	diagnosticsPath, ok := paths["/api/v1/system/diagnostics-report/export"].(map[string]any)
	require.True(t, ok)
	diagnosticsGet, ok := diagnosticsPath["get"].(map[string]any)
	require.True(t, ok)
	assert.Equal(t, "Export diagnostics report", diagnosticsGet["summary"])
	assert.Contains(t, diagnosticsGet["x-aegisnas-roles"], "read_only")
	parameters, ok := diagnosticsGet["parameters"].([]any)
	require.True(t, ok)
	require.NotEmpty(t, parameters)

	scheduledDiagnosticsPath, ok := paths["/api/v1/system/diagnostics-exports/download"].(map[string]any)
	require.True(t, ok)
	scheduledDiagnosticsGet, ok := scheduledDiagnosticsPath["get"].(map[string]any)
	require.True(t, ok)
	assert.Equal(t, "Download scheduled diagnostics export", scheduledDiagnosticsGet["summary"])

	scheduledSupportBundlePath, ok := paths["/api/v1/system/support-bundle-exports/download"].(map[string]any)
	require.True(t, ok)
	scheduledSupportBundleGet, ok := scheduledSupportBundlePath["get"].(map[string]any)
	require.True(t, ok)
	assert.Equal(t, "Download scheduled support bundle export", scheduledSupportBundleGet["summary"])

	integrationHistoryPath, ok := paths["/api/v1/system/integration-history/export"].(map[string]any)
	require.True(t, ok)
	integrationHistoryGet, ok := integrationHistoryPath["get"].(map[string]any)
	require.True(t, ok)
	assert.Equal(t, "Export integration automation history", integrationHistoryGet["summary"])

	scheduledIntegrationPath, ok := paths["/api/v1/system/integration-exports/download"].(map[string]any)
	require.True(t, ok)
	scheduledIntegrationGet, ok := scheduledIntegrationPath["get"].(map[string]any)
	require.True(t, ok)
	assert.Equal(t, "Download scheduled integration export", scheduledIntegrationGet["summary"])

	scheduledHAPath, ok := paths["/api/v1/system/ha/exports/download"].(map[string]any)
	require.True(t, ok)
	scheduledHAGet, ok := scheduledHAPath["get"].(map[string]any)
	require.True(t, ok)
	assert.Equal(t, "Download scheduled HA export", scheduledHAGet["summary"])

	scheduledNetworkPath, ok := paths["/api/v1/system/network-exports/download"].(map[string]any)
	require.True(t, ok)
	scheduledNetworkGet, ok := scheduledNetworkPath["get"].(map[string]any)
	require.True(t, ok)
	assert.Equal(t, "Download scheduled network export", scheduledNetworkGet["summary"])

	scheduledUpstreamAAAPath, ok := paths["/api/v1/system/upstream-aaa-exports/download"].(map[string]any)
	require.True(t, ok)
	scheduledUpstreamAAAGet, ok := scheduledUpstreamAAAPath["get"].(map[string]any)
	require.True(t, ok)
	assert.Equal(t, "Download scheduled upstream AAA export", scheduledUpstreamAAAGet["summary"])

	scheduledUpgradeReadinessPath, ok := paths["/api/v1/system/upgrade-readiness-exports/download"].(map[string]any)
	require.True(t, ok)
	scheduledUpgradeReadinessGet, ok := scheduledUpgradeReadinessPath["get"].(map[string]any)
	require.True(t, ok)
	assert.Equal(t, "Download scheduled upgrade readiness export", scheduledUpgradeReadinessGet["summary"])

	auditHistoryPath, ok := paths["/api/v1/system/audit-history/export"].(map[string]any)
	require.True(t, ok)
	auditHistoryGet, ok := auditHistoryPath["get"].(map[string]any)
	require.True(t, ok)
	assert.Equal(t, "Export audit history", auditHistoryGet["summary"])

	scheduledAuditPath, ok := paths["/api/v1/system/audit-exports/download"].(map[string]any)
	require.True(t, ok)
	scheduledAuditGet, ok := scheduledAuditPath["get"].(map[string]any)
	require.True(t, ok)
	assert.Equal(t, "Download scheduled audit export", scheduledAuditGet["summary"])

	sessionHistoryPath, ok := paths["/api/v1/system/session-history/export"].(map[string]any)
	require.True(t, ok)
	sessionHistoryGet, ok := sessionHistoryPath["get"].(map[string]any)
	require.True(t, ok)
	assert.Equal(t, "Export session and accounting history", sessionHistoryGet["summary"])

	sessionAnalyticsPath, ok := paths["/api/v1/system/session-analytics/export"].(map[string]any)
	require.True(t, ok)
	sessionAnalyticsGet, ok := sessionAnalyticsPath["get"].(map[string]any)
	require.True(t, ok)
	assert.Equal(t, "Export session activity analytics", sessionAnalyticsGet["summary"])
	voucherAnalyticsPath, ok := paths["/api/v1/system/voucher-analytics/export"].(map[string]any)
	require.True(t, ok)
	voucherAnalyticsGet, ok := voucherAnalyticsPath["get"].(map[string]any)
	require.True(t, ok)
	assert.Equal(t, "Export voucher inventory and usage analytics", voucherAnalyticsGet["summary"])
	voucherAgingPath, ok := paths["/api/v1/system/voucher-aging-analytics/export"].(map[string]any)
	require.True(t, ok)
	voucherAgingGet, ok := voucherAgingPath["get"].(map[string]any)
	require.True(t, ok)
	assert.Equal(t, "Export voucher stock aging analytics", voucherAgingGet["summary"])
	voucherRedemptionPath, ok := paths["/api/v1/system/voucher-redemption-analytics/export"].(map[string]any)
	require.True(t, ok)
	voucherRedemptionGet, ok := voucherRedemptionPath["get"].(map[string]any)
	require.True(t, ok)
	assert.Equal(t, "Export voucher redemption analytics", voucherRedemptionGet["summary"])
	voucherExpiryPath, ok := paths["/api/v1/system/voucher-expiry-analytics/export"].(map[string]any)
	require.True(t, ok)
	voucherExpiryGet, ok := voucherExpiryPath["get"].(map[string]any)
	require.True(t, ok)
	assert.Equal(t, "Export voucher expiry analytics", voucherExpiryGet["summary"])
	voucherRedemptionScheduledPath, ok := paths["/api/v1/system/voucher-redemption-analytics-exports/download"].(map[string]any)
	require.True(t, ok)
	voucherRedemptionScheduledGet, ok := voucherRedemptionScheduledPath["get"].(map[string]any)
	require.True(t, ok)
	assert.Equal(t, "Download scheduled voucher redemption analytics export", voucherRedemptionScheduledGet["summary"])
	voucherExpiryScheduledPath, ok := paths["/api/v1/system/voucher-expiry-analytics-exports/download"].(map[string]any)
	require.True(t, ok)
	voucherExpiryScheduledGet, ok := voucherExpiryScheduledPath["get"].(map[string]any)
	require.True(t, ok)
	assert.Equal(t, "Download scheduled voucher expiry analytics export", voucherExpiryScheduledGet["summary"])
	voucherAnalyticsScheduledPath, ok := paths["/api/v1/system/voucher-analytics-exports/download"].(map[string]any)
	require.True(t, ok)
	voucherAnalyticsScheduledGet, ok := voucherAnalyticsScheduledPath["get"].(map[string]any)
	require.True(t, ok)
	assert.Equal(t, "Download scheduled voucher analytics export", voucherAnalyticsScheduledGet["summary"])
	voucherAgingScheduledPath, ok := paths["/api/v1/system/voucher-aging-analytics-exports/download"].(map[string]any)
	require.True(t, ok)
	voucherAgingScheduledGet, ok := voucherAgingScheduledPath["get"].(map[string]any)
	require.True(t, ok)
	assert.Equal(t, "Download scheduled voucher aging analytics export", voucherAgingScheduledGet["summary"])

	guestDeliveryPath, ok := paths["/api/v1/system/guest-delivery-analytics/export"].(map[string]any)
	require.True(t, ok)
	guestDeliveryGet, ok := guestDeliveryPath["get"].(map[string]any)
	require.True(t, ok)
	assert.Equal(t, "Export guest delivery analytics", guestDeliveryGet["summary"])
	guestRejectionPath, ok := paths["/api/v1/system/guest-rejection-analytics/export"].(map[string]any)
	require.True(t, ok)
	guestRejectionGet, ok := guestRejectionPath["get"].(map[string]any)
	require.True(t, ok)
	assert.Equal(t, "Export guest rejection analytics", guestRejectionGet["summary"])
	guestRejectionScheduledPath, ok := paths["/api/v1/system/guest-rejection-analytics-exports/download"].(map[string]any)
	require.True(t, ok)
	guestRejectionScheduledGet, ok := guestRejectionScheduledPath["get"].(map[string]any)
	require.True(t, ok)
	assert.Equal(t, "Download scheduled guest rejection analytics export", guestRejectionScheduledGet["summary"])

	guestInvitePath, ok := paths["/api/v1/system/guest-invite-analytics/export"].(map[string]any)
	require.True(t, ok)
	guestInviteGet, ok := guestInvitePath["get"].(map[string]any)
	require.True(t, ok)
	assert.Equal(t, "Export guest invite analytics", guestInviteGet["summary"])
	guestConversionPath, ok := paths["/api/v1/system/guest-conversion-analytics/export"].(map[string]any)
	require.True(t, ok)
	guestConversionGet, ok := guestConversionPath["get"].(map[string]any)
	require.True(t, ok)
	assert.Equal(t, "Export guest conversion analytics", guestConversionGet["summary"])
	guestConversionScheduledPath, ok := paths["/api/v1/system/guest-conversion-analytics-exports/download"].(map[string]any)
	require.True(t, ok)
	guestConversionScheduledGet, ok := guestConversionScheduledPath["get"].(map[string]any)
	require.True(t, ok)
	assert.Equal(t, "Download scheduled guest conversion analytics export", guestConversionScheduledGet["summary"])
	guestInviteScheduledPath, ok := paths["/api/v1/system/guest-invite-analytics-exports/download"].(map[string]any)
	require.True(t, ok)
	guestInviteScheduledGet, ok := guestInviteScheduledPath["get"].(map[string]any)
	require.True(t, ok)
	assert.Equal(t, "Download scheduled guest invite analytics export", guestInviteScheduledGet["summary"])

	guestDeliveryFailuresPath, ok := paths["/api/v1/system/guest-delivery-failures/export"].(map[string]any)
	require.True(t, ok)
	guestDeliveryFailuresGet, ok := guestDeliveryFailuresPath["get"].(map[string]any)
	require.True(t, ok)
	assert.Equal(t, "Export guest delivery failure analytics", guestDeliveryFailuresGet["summary"])

	guestSponsorPath, ok := paths["/api/v1/system/guest-sponsor-analytics/export"].(map[string]any)
	require.True(t, ok)
	guestSponsorGet, ok := guestSponsorPath["get"].(map[string]any)
	require.True(t, ok)
	assert.Equal(t, "Export sponsor approval analytics", guestSponsorGet["summary"])

	scheduledGuestDeliveryPath, ok := paths["/api/v1/system/guest-delivery-analytics-exports/download"].(map[string]any)
	require.True(t, ok)
	scheduledGuestDeliveryGet, ok := scheduledGuestDeliveryPath["get"].(map[string]any)
	require.True(t, ok)
	assert.Equal(t, "Download scheduled guest delivery analytics export", scheduledGuestDeliveryGet["summary"])

	scheduledGuestDeliveryFailuresPath, ok := paths["/api/v1/system/guest-delivery-failures-exports/download"].(map[string]any)
	require.True(t, ok)
	scheduledGuestDeliveryFailuresGet, ok := scheduledGuestDeliveryFailuresPath["get"].(map[string]any)
	require.True(t, ok)
	assert.Equal(t, "Download scheduled guest delivery failure export", scheduledGuestDeliveryFailuresGet["summary"])

	scheduledGuestSponsorPath, ok := paths["/api/v1/system/guest-sponsor-analytics-exports/download"].(map[string]any)
	require.True(t, ok)
	scheduledGuestSponsorGet, ok := scheduledGuestSponsorPath["get"].(map[string]any)
	require.True(t, ok)
	assert.Equal(t, "Download scheduled guest sponsor analytics export", scheduledGuestSponsorGet["summary"])

	scheduledSessionAnalyticsPath, ok := paths["/api/v1/system/session-analytics-exports/download"].(map[string]any)
	require.True(t, ok)
	scheduledSessionAnalyticsGet, ok := scheduledSessionAnalyticsPath["get"].(map[string]any)
	require.True(t, ok)
	assert.Equal(t, "Download scheduled session analytics export", scheduledSessionAnalyticsGet["summary"])

	scheduledSessionPath, ok := paths["/api/v1/system/session-exports/download"].(map[string]any)
	require.True(t, ok)
	scheduledSessionGet, ok := scheduledSessionPath["get"].(map[string]any)
	require.True(t, ok)
	assert.Equal(t, "Download scheduled session export", scheduledSessionGet["summary"])

	components, ok := payload["components"].(map[string]any)
	require.True(t, ok)
	securitySchemes, ok := components["securitySchemes"].(map[string]any)
	require.True(t, ok)
	require.Contains(t, securitySchemes, "bearerAuth")
}
