package adminapi

import (
	"encoding/json"
	"net/http"
	"net/http/httptest"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

func TestHandleGetOpenAPI(t *testing.T) {
	_ = prepareSupportBundleTestConfig(t)

	req := httptest.NewRequest(http.MethodGet, "https://appliance.example.test/api/v1/openapi.json", nil)
	rec := httptest.NewRecorder()

	HandleGetOpenAPI(rec, req)

	require.Equal(t, http.StatusOK, rec.Code)
	assert.Equal(t, "application/json", rec.Header().Get("Content-Type"))

	var payload map[string]any
	require.NoError(t, json.Unmarshal(rec.Body.Bytes(), &payload))

	assert.Equal(t, "3.1.0", payload["openapi"])

	info, ok := payload["info"].(map[string]any)
	require.True(t, ok)
	assert.Equal(t, "AegisNAS Admin API", info["title"])

	paths, ok := payload["paths"].(map[string]any)
	require.True(t, ok)
	aclPoliciesPath, ok := paths["/api/v1/acl-policies"].(map[string]any)
	require.True(t, ok)
	aclPoliciesGet, ok := aclPoliciesPath["get"].(map[string]any)
	require.True(t, ok)
	assert.Equal(t, "List ACL policies", aclPoliciesGet["summary"])

	statusPath, ok := paths["/api/v1/system/status"].(map[string]any)
	require.True(t, ok)
	statusGet, ok := statusPath["get"].(map[string]any)
	require.True(t, ok)
	assert.Equal(t, "Read system runtime status", statusGet["summary"])
	assert.Contains(t, statusGet["x-aegisnas-roles"], "read_only")

	vendorCompatibilityPath, ok := paths["/api/v1/system/vendor-compatibility"].(map[string]any)
	require.True(t, ok)
	vendorCompatibilityGet, ok := vendorCompatibilityPath["get"].(map[string]any)
	require.True(t, ok)
	assert.Equal(t, "Read vendor compatibility catalog", vendorCompatibilityGet["summary"])
	assert.Contains(t, vendorCompatibilityGet["x-aegisnas-roles"], "read_only")

	vendorIdentityPath, ok := paths["/api/v1/system/vendor-identity"].(map[string]any)
	require.True(t, ok)
	vendorIdentityGet, ok := vendorIdentityPath["get"].(map[string]any)
	require.True(t, ok)
	assert.Equal(t, "Read AegisNAS vendor identity lifecycle", vendorIdentityGet["summary"])
	assert.Contains(t, vendorIdentityGet["x-aegisnas-roles"], "read_only")

	dictionaryReleasePath, ok := paths["/api/v1/system/dictionary-release-profiles"].(map[string]any)
	require.True(t, ok)
	dictionaryReleaseGet, ok := dictionaryReleasePath["get"].(map[string]any)
	require.True(t, ok)
	assert.Equal(t, "Read dictionary release profiles", dictionaryReleaseGet["summary"])
	assert.Contains(t, dictionaryReleaseGet["x-aegisnas-roles"], "read_only")

	compatibilityEvidencePath, ok := paths["/api/v1/system/compatibility-evidence"].(map[string]any)
	require.True(t, ok)
	compatibilityEvidenceGet, ok := compatibilityEvidencePath["get"].(map[string]any)
	require.True(t, ok)
	assert.Equal(t, "Read compatibility evidence states", compatibilityEvidenceGet["summary"])
	assert.Contains(t, compatibilityEvidenceGet["x-aegisnas-roles"], "read_only")

	vsaCodecPath, ok := paths["/api/v1/system/vsa-codec"].(map[string]any)
	require.True(t, ok)
	vsaCodecGet, ok := vsaCodecPath["get"].(map[string]any)
	require.True(t, ok)
	assert.Equal(t, "Read VSA codec capabilities", vsaCodecGet["summary"])
	assert.Contains(t, vsaCodecGet["x-aegisnas-roles"], "read_only")

	opaquePassThroughPath, ok := paths["/api/v1/system/opaque-passthrough"].(map[string]any)
	require.True(t, ok)
	opaquePassThroughGet, ok := opaquePassThroughPath["get"].(map[string]any)
	require.True(t, ok)
	assert.Equal(t, "Read opaque attribute pass-through policy", opaquePassThroughGet["summary"])
	assert.Contains(t, opaquePassThroughGet["x-aegisnas-roles"], "read_only")

	radiusHardeningPath, ok := paths["/api/v1/system/radius-hardening"].(map[string]any)
	require.True(t, ok)
	radiusHardeningGet, ok := radiusHardeningPath["get"].(map[string]any)
	require.True(t, ok)
	assert.Equal(t, "Read RADIUS packet hardening policy", radiusHardeningGet["summary"])
	assert.Contains(t, radiusHardeningGet["x-aegisnas-roles"], "read_only")

	radsecCredentialsPath, ok := paths["/api/v1/system/radsec-credentials"].(map[string]any)
	require.True(t, ok)
	radsecCredentialsGet, ok := radsecCredentialsPath["get"].(map[string]any)
	require.True(t, ok)
	assert.Equal(t, "Read RadSec credential and rotation state", radsecCredentialsGet["summary"])
	assert.Contains(t, radsecCredentialsGet["x-aegisnas-roles"], "read_only")

	certificateLifecyclePath, ok := paths["/api/v1/system/certificate-lifecycle"].(map[string]any)
	require.True(t, ok)
	certificateLifecycleGet, ok := certificateLifecyclePath["get"].(map[string]any)
	require.True(t, ok)
	assert.Equal(t, "Read enterprise certificate lifecycle state", certificateLifecycleGet["summary"])
	assert.Contains(t, certificateLifecycleGet["x-aegisnas-roles"], "read_only")
	certificateLifecycleEvaluatePath, ok := paths["/api/v1/system/certificate-lifecycle/evaluate"].(map[string]any)
	require.True(t, ok)
	certificateLifecycleEvaluatePost, ok := certificateLifecycleEvaluatePath["post"].(map[string]any)
	require.True(t, ok)
	assert.Equal(t, "Evaluate a certificate lifecycle request", certificateLifecycleEvaluatePost["summary"])
	assert.Contains(t, certificateLifecycleEvaluatePost["x-aegisnas-roles"], "ops_admin")

	supplicantLifecyclePath, ok := paths["/api/v1/system/supplicant-lifecycle"].(map[string]any)
	require.True(t, ok)
	supplicantLifecycleGet, ok := supplicantLifecyclePath["get"].(map[string]any)
	require.True(t, ok)
	assert.Equal(t, "Read password and supplicant lifecycle state", supplicantLifecycleGet["summary"])
	assert.Contains(t, supplicantLifecycleGet["x-aegisnas-roles"], "read_only")
	supplicantLifecycleEvaluatePath, ok := paths["/api/v1/system/supplicant-lifecycle/evaluate"].(map[string]any)
	require.True(t, ok)
	supplicantLifecycleEvaluatePost, ok := supplicantLifecycleEvaluatePath["post"].(map[string]any)
	require.True(t, ok)
	assert.Equal(t, "Evaluate a password or supplicant lifecycle request", supplicantLifecycleEvaluatePost["summary"])
	assert.Contains(t, supplicantLifecycleEvaluatePost["x-aegisnas-roles"], "ops_admin")
	supplicantLifecycleProfilePath, ok := paths["/api/v1/system/supplicant-lifecycle/profile"].(map[string]any)
	require.True(t, ok)
	supplicantLifecycleProfilePost, ok := supplicantLifecycleProfilePath["post"].(map[string]any)
	require.True(t, ok)
	assert.Equal(t, "Render a signed supplicant profile package", supplicantLifecycleProfilePost["summary"])
	assert.Contains(t, supplicantLifecycleProfilePost["x-aegisnas-roles"], "ops_admin")

	policyEnginePath, ok := paths["/api/v1/system/policy-engine"].(map[string]any)
	require.True(t, ok)
	policyEngineGet, ok := policyEnginePath["get"].(map[string]any)
	require.True(t, ok)
	assert.Equal(t, "Read typed policy expression engine state", policyEngineGet["summary"])
	assert.Contains(t, policyEngineGet["x-aegisnas-roles"], "read_only")
	policyEngineValidatePath, ok := paths["/api/v1/system/policy-engine/validate"].(map[string]any)
	require.True(t, ok)
	policyEngineValidatePost, ok := policyEngineValidatePath["post"].(map[string]any)
	require.True(t, ok)
	assert.Equal(t, "Validate policy expression", policyEngineValidatePost["summary"])
	assert.Contains(t, policyEngineValidatePost["x-aegisnas-roles"], "ops_admin")
	policyEngineEvaluatePath, ok := paths["/api/v1/system/policy-engine/evaluate"].(map[string]any)
	require.True(t, ok)
	policyEngineEvaluatePost, ok := policyEngineEvaluatePath["post"].(map[string]any)
	require.True(t, ok)
	assert.Equal(t, "Evaluate typed policy request", policyEngineEvaluatePost["summary"])
	assert.Contains(t, policyEngineEvaluatePost["x-aegisnas-roles"], "ops_admin")
	policySetsPath, ok := paths["/api/v1/system/policy-sets"].(map[string]any)
	require.True(t, ok)
	policySetsGet, ok := policySetsPath["get"].(map[string]any)
	require.True(t, ok)
	assert.Equal(t, "Read versioned policy set governance", policySetsGet["summary"])
	assert.Contains(t, policySetsGet["x-aegisnas-roles"], "read_only")
	policySetVersionsPath, ok := paths["/api/v1/system/policy-sets/versions"].(map[string]any)
	require.True(t, ok)
	policySetVersionsPost, ok := policySetVersionsPath["post"].(map[string]any)
	require.True(t, ok)
	assert.Equal(t, "Create policy set version", policySetVersionsPost["summary"])
	assert.Contains(t, policySetVersionsPost["x-aegisnas-roles"], "ops_admin")
	policySetApprovePath, ok := paths["/api/v1/system/policy-sets/versions/{id}/approve"].(map[string]any)
	require.True(t, ok)
	policySetApprovePost, ok := policySetApprovePath["post"].(map[string]any)
	require.True(t, ok)
	assert.Equal(t, "Approve policy set version", policySetApprovePost["summary"])
	assert.Contains(t, policySetApprovePost["x-aegisnas-roles"], "super_admin")
	policySetActivatePath, ok := paths["/api/v1/system/policy-sets/versions/{id}/activate"].(map[string]any)
	require.True(t, ok)
	policySetActivatePost, ok := policySetActivatePath["post"].(map[string]any)
	require.True(t, ok)
	assert.Equal(t, "Activate approved policy set version", policySetActivatePost["summary"])
	assert.Contains(t, policySetActivatePost["x-aegisnas-roles"], "super_admin")
	policySetSimulatePath, ok := paths["/api/v1/system/policy-sets/versions/{id}/simulate"].(map[string]any)
	require.True(t, ok)
	policySetSimulatePost, ok := policySetSimulatePath["post"].(map[string]any)
	require.True(t, ok)
	assert.Equal(t, "Simulate policy set version", policySetSimulatePost["summary"])
	assert.Contains(t, policySetSimulatePost["x-aegisnas-roles"], "ops_admin")
	policySetAnalyzePath, ok := paths["/api/v1/system/policy-sets/versions/{id}/analyze"].(map[string]any)
	require.True(t, ok)
	policySetAnalyzePost, ok := policySetAnalyzePath["post"].(map[string]any)
	require.True(t, ok)
	assert.Equal(t, "Analyze policy set version blast radius", policySetAnalyzePost["summary"])
	assert.Contains(t, policySetAnalyzePost["x-aegisnas-roles"], "ops_admin")
	policySetAnalysesPath, ok := paths["/api/v1/system/policy-sets/analyses"].(map[string]any)
	require.True(t, ok)
	policySetAnalysesGet, ok := policySetAnalysesPath["get"].(map[string]any)
	require.True(t, ok)
	assert.Equal(t, "List policy simulation analyses", policySetAnalysesGet["summary"])

	nasEnrollPath, ok := paths["/api/v1/nas/enroll"].(map[string]any)
	require.True(t, ok)
	nasEnrollPost, ok := nasEnrollPath["post"].(map[string]any)
	require.True(t, ok)
	assert.Equal(t, "Bootstrap dynamic NAS enrollment", nasEnrollPost["summary"])

	nasClientsPath, ok := paths["/api/v1/system/nas-clients"].(map[string]any)
	require.True(t, ok)
	nasClientsGet, ok := nasClientsPath["get"].(map[string]any)
	require.True(t, ok)
	assert.Equal(t, "Read dynamic NAS client lifecycle", nasClientsGet["summary"])
	assert.Contains(t, nasClientsGet["x-aegisnas-roles"], "read_only")

	proxyRoutesPath, ok := paths["/api/v1/system/proxy-routes"].(map[string]any)
	require.True(t, ok)
	proxyRoutesGet, ok := proxyRoutesPath["get"].(map[string]any)
	require.True(t, ok)
	assert.Equal(t, "Read RADIUS proxy routing table", proxyRoutesGet["summary"])
	assert.Contains(t, proxyRoutesGet["x-aegisnas-roles"], "read_only")

	transportPolicyPath, ok := paths["/api/v1/system/transport-policy"].(map[string]any)
	require.True(t, ok)
	transportPolicyGet, ok := transportPolicyPath["get"].(map[string]any)
	require.True(t, ok)
	assert.Equal(t, "Read RADIUS transport downgrade policy", transportPolicyGet["summary"])
	assert.Contains(t, transportPolicyGet["x-aegisnas-roles"], "read_only")

	proxyPolicyPath, ok := paths["/api/v1/system/proxy-policy"].(map[string]any)
	require.True(t, ok)
	proxyPolicyGet, ok := proxyPolicyPath["get"].(map[string]any)
	require.True(t, ok)
	assert.Equal(t, "Read RADIUS proxy loop and attribute policy", proxyPolicyGet["summary"])
	assert.Contains(t, proxyPolicyGet["x-aegisnas-roles"], "read_only")

	accountingSpoolPath, ok := paths["/api/v1/system/accounting-spool"].(map[string]any)
	require.True(t, ok)
	accountingSpoolGet, ok := accountingSpoolPath["get"].(map[string]any)
	require.True(t, ok)
	assert.Equal(t, "Read durable RADIUS accounting spool state", accountingSpoolGet["summary"])
	assert.Contains(t, accountingSpoolGet["x-aegisnas-roles"], "read_only")
	accountingSpoolReplayPath, ok := paths["/api/v1/system/accounting-spool/replay"].(map[string]any)
	require.True(t, ok)
	accountingSpoolReplayPost, ok := accountingSpoolReplayPath["post"].(map[string]any)
	require.True(t, ok)
	assert.Equal(t, "Replay due durable RADIUS accounting records", accountingSpoolReplayPost["summary"])
	assert.Contains(t, accountingSpoolReplayPost["x-aegisnas-roles"], "ops_admin")

	sqlAccountingPath, ok := paths["/api/v1/system/sql-accounting"].(map[string]any)
	require.True(t, ok)
	sqlAccountingGet, ok := sqlAccountingPath["get"].(map[string]any)
	require.True(t, ok)
	assert.Equal(t, "Read FreeRADIUS SQL accounting reconciliation state", sqlAccountingGet["summary"])
	assert.Contains(t, sqlAccountingGet["x-aegisnas-roles"], "read_only")
	sqlAccountingReconcilePath, ok := paths["/api/v1/system/sql-accounting/reconcile"].(map[string]any)
	require.True(t, ok)
	sqlAccountingReconcilePost, ok := sqlAccountingReconcilePath["post"].(map[string]any)
	require.True(t, ok)
	assert.Equal(t, "Reconcile FreeRADIUS SQL accounting rows", sqlAccountingReconcilePost["summary"])
	assert.Contains(t, sqlAccountingReconcilePost["x-aegisnas-roles"], "ops_admin")

	fallbackPolicyPath, ok := paths["/api/v1/system/fallback-policy"].(map[string]any)
	require.True(t, ok)
	fallbackPolicyGet, ok := fallbackPolicyPath["get"].(map[string]any)
	require.True(t, ok)
	assert.Equal(t, "Read upstream outage fallback policy", fallbackPolicyGet["summary"])
	assert.Contains(t, fallbackPolicyGet["x-aegisnas-roles"], "read_only")

	secretProvidersPath, ok := paths["/api/v1/system/secret-providers"].(map[string]any)
	require.True(t, ok)
	secretProvidersGet, ok := secretProvidersPath["get"].(map[string]any)
	require.True(t, ok)
	assert.Equal(t, "Read secret provider readiness", secretProvidersGet["summary"])
	assert.Contains(t, secretProvidersGet["x-aegisnas-roles"], "read_only")

	databasePath, ok := paths["/api/v1/system/database"].(map[string]any)
	require.True(t, ok)
	databaseGet, ok := databasePath["get"].(map[string]any)
	require.True(t, ok)
	assert.Equal(t, "Read database data-plane readiness", databaseGet["summary"])
	assert.Contains(t, databaseGet["x-aegisnas-roles"], "read_only")

	vendorIdentityPreviewPath, ok := paths["/api/v1/system/vendor-identity/migrations/preview"].(map[string]any)
	require.True(t, ok)
	vendorIdentityPreviewPost, ok := vendorIdentityPreviewPath["post"].(map[string]any)
	require.True(t, ok)
	assert.Contains(t, vendorIdentityPreviewPost["x-aegisnas-roles"], "super_admin")
	attributeRegistryPath, ok := paths["/api/v1/system/attribute-registry"].(map[string]any)
	require.True(t, ok)
	attributeRegistryGet, ok := attributeRegistryPath["get"].(map[string]any)
	require.True(t, ok)
	assert.Equal(t, "Read the generated typed attribute registry", attributeRegistryGet["summary"])
	assert.Contains(t, attributeRegistryGet["x-aegisnas-roles"], "read_only")

	productionReadinessPath, ok := paths["/api/v1/system/production-readiness"].(map[string]any)
	require.True(t, ok)
	productionReadinessGet, ok := productionReadinessPath["get"].(map[string]any)
	require.True(t, ok)
	assert.Equal(t, "Read production readiness report", productionReadinessGet["summary"])
	assert.Contains(t, productionReadinessGet["x-aegisnas-roles"], "read_only")

	vendorObservabilityPath, ok := paths["/api/v1/system/vendor-observability"].(map[string]any)
	require.True(t, ok)
	vendorObservabilityGet, ok := vendorObservabilityPath["get"].(map[string]any)
	require.True(t, ok)
	assert.Equal(t, "Read vendor observability counters", vendorObservabilityGet["summary"])
	assert.Contains(t, vendorObservabilityGet["x-aegisnas-roles"], "read_only")

	vendorObservabilityExportPath, ok := paths["/api/v1/system/vendor-observability/export"].(map[string]any)
	require.True(t, ok)
	vendorObservabilityExportGet, ok := vendorObservabilityExportPath["get"].(map[string]any)
	require.True(t, ok)
	assert.Equal(t, "Export vendor observability counters", vendorObservabilityExportGet["summary"])
	assert.Contains(t, vendorObservabilityExportGet["x-aegisnas-roles"], "read_only")

	controllerAdaptersPath, ok := paths["/api/v1/system/controller-adapters"].(map[string]any)
	require.True(t, ok)
	controllerAdaptersGet, ok := controllerAdaptersPath["get"].(map[string]any)
	require.True(t, ok)
	assert.Equal(t, "Read controller adapter catalog", controllerAdaptersGet["summary"])
	assert.Contains(t, controllerAdaptersGet["x-aegisnas-roles"], "read_only")

	controllerSyncPreviewPath, ok := paths["/api/v1/system/controller-sync/preview"].(map[string]any)
	require.True(t, ok)
	controllerSyncPreviewGet, ok := controllerSyncPreviewPath["get"].(map[string]any)
	require.True(t, ok)
	assert.Equal(t, "Preview controller policy synchronization", controllerSyncPreviewGet["summary"])

	controllerSyncPath, ok := paths["/api/v1/system/controller-sync"].(map[string]any)
	require.True(t, ok)
	controllerSyncPost, ok := controllerSyncPath["post"].(map[string]any)
	require.True(t, ok)
	assert.Equal(t, "Run controller policy synchronization", controllerSyncPost["summary"])
	assert.Contains(t, controllerSyncPost["x-aegisnas-roles"], "ops_admin")

	vendorReplyPreviewPath, ok := paths["/api/v1/system/vendor-reply-preview"].(map[string]any)
	require.True(t, ok)
	vendorReplyPreviewPost, ok := vendorReplyPreviewPath["post"].(map[string]any)
	require.True(t, ok)
	assert.Equal(t, "Preview vendor reply attributes", vendorReplyPreviewPost["summary"])
	assert.Contains(t, vendorReplyPreviewPost["x-aegisnas-roles"], "read_only")

	profileObservationPath, ok := paths["/api/v1/devices/profile-observations"].(map[string]any)
	require.True(t, ok)
	profileObservationPost, ok := profileObservationPath["post"].(map[string]any)
	require.True(t, ok)
	assert.Equal(t, "Record device profile observation", profileObservationPost["summary"])
	assert.Contains(t, profileObservationPost["x-aegisnas-roles"], "ops_admin")
	assert.NotContains(t, profileObservationPost["x-aegisnas-roles"], "guest_admin")

	certificateRevokePath, ok := paths["/api/v1/devices/certificates/{id}/revoke"].(map[string]any)
	require.True(t, ok)
	certificateRevokePost, ok := certificateRevokePath["post"].(map[string]any)
	require.True(t, ok)
	assert.Equal(t, "Revoke device certificate", certificateRevokePost["summary"])
	assert.Contains(t, certificateRevokePost["x-aegisnas-roles"], "ops_admin")
	assert.NotContains(t, certificateRevokePost["x-aegisnas-roles"], "guest_admin")

	certificateCRLPath, ok := paths["/api/v1/devices/certificates/crl"].(map[string]any)
	require.True(t, ok)
	certificateCRLGet, ok := certificateCRLPath["get"].(map[string]any)
	require.True(t, ok)
	assert.Equal(t, "Download device certificate revocation list", certificateCRLGet["summary"])
	assert.Contains(t, certificateCRLGet["x-aegisnas-roles"], "read_only")

	specPath, ok := paths["/api/v1/openapi.json"].(map[string]any)
	require.True(t, ok)
	specGet, ok := specPath["get"].(map[string]any)
	require.True(t, ok)
	assert.Equal(t, "public", specGet["x-aegisnas-visibility"])

	diagnosticsPath, ok := paths["/api/v1/system/diagnostics-report/export"].(map[string]any)
	require.True(t, ok)
	diagnosticsGet, ok := diagnosticsPath["get"].(map[string]any)
	require.True(t, ok)
	assert.Equal(t, "Export diagnostics report", diagnosticsGet["summary"])
	assert.Contains(t, diagnosticsGet["x-aegisnas-roles"], "read_only")
	parameters, ok := diagnosticsGet["parameters"].([]any)
	require.True(t, ok)
	require.NotEmpty(t, parameters)

	scheduledDiagnosticsPath, ok := paths["/api/v1/system/diagnostics-exports/download"].(map[string]any)
	require.True(t, ok)
	scheduledDiagnosticsGet, ok := scheduledDiagnosticsPath["get"].(map[string]any)
	require.True(t, ok)
	assert.Equal(t, "Download scheduled diagnostics export", scheduledDiagnosticsGet["summary"])

	scheduledSupportBundlePath, ok := paths["/api/v1/system/support-bundle-exports/download"].(map[string]any)
	require.True(t, ok)
	scheduledSupportBundleGet, ok := scheduledSupportBundlePath["get"].(map[string]any)
	require.True(t, ok)
	assert.Equal(t, "Download scheduled support bundle export", scheduledSupportBundleGet["summary"])

	integrationHistoryPath, ok := paths["/api/v1/system/integration-history/export"].(map[string]any)
	require.True(t, ok)
	integrationHistoryGet, ok := integrationHistoryPath["get"].(map[string]any)
	require.True(t, ok)
	assert.Equal(t, "Export integration automation history", integrationHistoryGet["summary"])

	scheduledIntegrationPath, ok := paths["/api/v1/system/integration-exports/download"].(map[string]any)
	require.True(t, ok)
	scheduledIntegrationGet, ok := scheduledIntegrationPath["get"].(map[string]any)
	require.True(t, ok)
	assert.Equal(t, "Download scheduled integration export", scheduledIntegrationGet["summary"])

	scheduledHAPath, ok := paths["/api/v1/system/ha/exports/download"].(map[string]any)
	require.True(t, ok)
	scheduledHAGet, ok := scheduledHAPath["get"].(map[string]any)
	require.True(t, ok)
	assert.Equal(t, "Download scheduled HA export", scheduledHAGet["summary"])

	scheduledNetworkPath, ok := paths["/api/v1/system/network-exports/download"].(map[string]any)
	require.True(t, ok)
	scheduledNetworkGet, ok := scheduledNetworkPath["get"].(map[string]any)
	require.True(t, ok)
	assert.Equal(t, "Download scheduled network export", scheduledNetworkGet["summary"])

	scheduledUpstreamAAAPath, ok := paths["/api/v1/system/upstream-aaa-exports/download"].(map[string]any)
	require.True(t, ok)
	scheduledUpstreamAAAGet, ok := scheduledUpstreamAAAPath["get"].(map[string]any)
	require.True(t, ok)
	assert.Equal(t, "Download scheduled upstream AAA export", scheduledUpstreamAAAGet["summary"])

	scheduledUpgradeReadinessPath, ok := paths["/api/v1/system/upgrade-readiness-exports/download"].(map[string]any)
	require.True(t, ok)
	scheduledUpgradeReadinessGet, ok := scheduledUpgradeReadinessPath["get"].(map[string]any)
	require.True(t, ok)
	assert.Equal(t, "Download scheduled upgrade readiness export", scheduledUpgradeReadinessGet["summary"])

	auditHistoryPath, ok := paths["/api/v1/system/audit-history/export"].(map[string]any)
	require.True(t, ok)
	auditHistoryGet, ok := auditHistoryPath["get"].(map[string]any)
	require.True(t, ok)
	assert.Equal(t, "Export audit history", auditHistoryGet["summary"])

	scheduledAuditPath, ok := paths["/api/v1/system/audit-exports/download"].(map[string]any)
	require.True(t, ok)
	scheduledAuditGet, ok := scheduledAuditPath["get"].(map[string]any)
	require.True(t, ok)
	assert.Equal(t, "Download scheduled audit export", scheduledAuditGet["summary"])

	sessionHistoryPath, ok := paths["/api/v1/system/session-history/export"].(map[string]any)
	require.True(t, ok)
	sessionHistoryGet, ok := sessionHistoryPath["get"].(map[string]any)
	require.True(t, ok)
	assert.Equal(t, "Export session and accounting history", sessionHistoryGet["summary"])

	sessionAnalyticsPath, ok := paths["/api/v1/system/session-analytics/export"].(map[string]any)
	require.True(t, ok)
	sessionAnalyticsGet, ok := sessionAnalyticsPath["get"].(map[string]any)
	require.True(t, ok)
	assert.Equal(t, "Export session activity analytics", sessionAnalyticsGet["summary"])
	voucherAnalyticsPath, ok := paths["/api/v1/system/voucher-analytics/export"].(map[string]any)
	require.True(t, ok)
	voucherAnalyticsGet, ok := voucherAnalyticsPath["get"].(map[string]any)
	require.True(t, ok)
	assert.Equal(t, "Export voucher inventory and usage analytics", voucherAnalyticsGet["summary"])
	voucherAgingPath, ok := paths["/api/v1/system/voucher-aging-analytics/export"].(map[string]any)
	require.True(t, ok)
	voucherAgingGet, ok := voucherAgingPath["get"].(map[string]any)
	require.True(t, ok)
	assert.Equal(t, "Export voucher stock aging analytics", voucherAgingGet["summary"])
	voucherRedemptionPath, ok := paths["/api/v1/system/voucher-redemption-analytics/export"].(map[string]any)
	require.True(t, ok)
	voucherRedemptionGet, ok := voucherRedemptionPath["get"].(map[string]any)
	require.True(t, ok)
	assert.Equal(t, "Export voucher redemption analytics", voucherRedemptionGet["summary"])
	voucherExpiryPath, ok := paths["/api/v1/system/voucher-expiry-analytics/export"].(map[string]any)
	require.True(t, ok)
	voucherExpiryGet, ok := voucherExpiryPath["get"].(map[string]any)
	require.True(t, ok)
	assert.Equal(t, "Export voucher expiry analytics", voucherExpiryGet["summary"])
	voucherRedemptionScheduledPath, ok := paths["/api/v1/system/voucher-redemption-analytics-exports/download"].(map[string]any)
	require.True(t, ok)
	voucherRedemptionScheduledGet, ok := voucherRedemptionScheduledPath["get"].(map[string]any)
	require.True(t, ok)
	assert.Equal(t, "Download scheduled voucher redemption analytics export", voucherRedemptionScheduledGet["summary"])
	voucherExpiryScheduledPath, ok := paths["/api/v1/system/voucher-expiry-analytics-exports/download"].(map[string]any)
	require.True(t, ok)
	voucherExpiryScheduledGet, ok := voucherExpiryScheduledPath["get"].(map[string]any)
	require.True(t, ok)
	assert.Equal(t, "Download scheduled voucher expiry analytics export", voucherExpiryScheduledGet["summary"])
	voucherAnalyticsScheduledPath, ok := paths["/api/v1/system/voucher-analytics-exports/download"].(map[string]any)
	require.True(t, ok)
	voucherAnalyticsScheduledGet, ok := voucherAnalyticsScheduledPath["get"].(map[string]any)
	require.True(t, ok)
	assert.Equal(t, "Download scheduled voucher analytics export", voucherAnalyticsScheduledGet["summary"])
	voucherAgingScheduledPath, ok := paths["/api/v1/system/voucher-aging-analytics-exports/download"].(map[string]any)
	require.True(t, ok)
	voucherAgingScheduledGet, ok := voucherAgingScheduledPath["get"].(map[string]any)
	require.True(t, ok)
	assert.Equal(t, "Download scheduled voucher aging analytics export", voucherAgingScheduledGet["summary"])

	guestDeliveryPath, ok := paths["/api/v1/system/guest-delivery-analytics/export"].(map[string]any)
	require.True(t, ok)
	guestDeliveryGet, ok := guestDeliveryPath["get"].(map[string]any)
	require.True(t, ok)
	assert.Equal(t, "Export guest delivery analytics", guestDeliveryGet["summary"])
	guestRejectionPath, ok := paths["/api/v1/system/guest-rejection-analytics/export"].(map[string]any)
	require.True(t, ok)
	guestRejectionGet, ok := guestRejectionPath["get"].(map[string]any)
	require.True(t, ok)
	assert.Equal(t, "Export guest rejection analytics", guestRejectionGet["summary"])
	guestRejectionScheduledPath, ok := paths["/api/v1/system/guest-rejection-analytics-exports/download"].(map[string]any)
	require.True(t, ok)
	guestRejectionScheduledGet, ok := guestRejectionScheduledPath["get"].(map[string]any)
	require.True(t, ok)
	assert.Equal(t, "Download scheduled guest rejection analytics export", guestRejectionScheduledGet["summary"])

	guestInvitePath, ok := paths["/api/v1/system/guest-invite-analytics/export"].(map[string]any)
	require.True(t, ok)
	guestInviteGet, ok := guestInvitePath["get"].(map[string]any)
	require.True(t, ok)
	assert.Equal(t, "Export guest invite analytics", guestInviteGet["summary"])
	guestConversionPath, ok := paths["/api/v1/system/guest-conversion-analytics/export"].(map[string]any)
	require.True(t, ok)
	guestConversionGet, ok := guestConversionPath["get"].(map[string]any)
	require.True(t, ok)
	assert.Equal(t, "Export guest conversion analytics", guestConversionGet["summary"])
	guestConversionScheduledPath, ok := paths["/api/v1/system/guest-conversion-analytics-exports/download"].(map[string]any)
	require.True(t, ok)
	guestConversionScheduledGet, ok := guestConversionScheduledPath["get"].(map[string]any)
	require.True(t, ok)
	assert.Equal(t, "Download scheduled guest conversion analytics export", guestConversionScheduledGet["summary"])
	guestInviteScheduledPath, ok := paths["/api/v1/system/guest-invite-analytics-exports/download"].(map[string]any)
	require.True(t, ok)
	guestInviteScheduledGet, ok := guestInviteScheduledPath["get"].(map[string]any)
	require.True(t, ok)
	assert.Equal(t, "Download scheduled guest invite analytics export", guestInviteScheduledGet["summary"])

	guestDeliveryFailuresPath, ok := paths["/api/v1/system/guest-delivery-failures/export"].(map[string]any)
	require.True(t, ok)
	guestDeliveryFailuresGet, ok := guestDeliveryFailuresPath["get"].(map[string]any)
	require.True(t, ok)
	assert.Equal(t, "Export guest delivery failure analytics", guestDeliveryFailuresGet["summary"])

	guestSponsorPath, ok := paths["/api/v1/system/guest-sponsor-analytics/export"].(map[string]any)
	require.True(t, ok)
	guestSponsorGet, ok := guestSponsorPath["get"].(map[string]any)
	require.True(t, ok)
	assert.Equal(t, "Export sponsor approval analytics", guestSponsorGet["summary"])

	scheduledGuestDeliveryPath, ok := paths["/api/v1/system/guest-delivery-analytics-exports/download"].(map[string]any)
	require.True(t, ok)
	scheduledGuestDeliveryGet, ok := scheduledGuestDeliveryPath["get"].(map[string]any)
	require.True(t, ok)
	assert.Equal(t, "Download scheduled guest delivery analytics export", scheduledGuestDeliveryGet["summary"])

	scheduledGuestDeliveryFailuresPath, ok := paths["/api/v1/system/guest-delivery-failures-exports/download"].(map[string]any)
	require.True(t, ok)
	scheduledGuestDeliveryFailuresGet, ok := scheduledGuestDeliveryFailuresPath["get"].(map[string]any)
	require.True(t, ok)
	assert.Equal(t, "Download scheduled guest delivery failure export", scheduledGuestDeliveryFailuresGet["summary"])

	scheduledGuestSponsorPath, ok := paths["/api/v1/system/guest-sponsor-analytics-exports/download"].(map[string]any)
	require.True(t, ok)
	scheduledGuestSponsorGet, ok := scheduledGuestSponsorPath["get"].(map[string]any)
	require.True(t, ok)
	assert.Equal(t, "Download scheduled guest sponsor analytics export", scheduledGuestSponsorGet["summary"])

	scheduledSessionAnalyticsPath, ok := paths["/api/v1/system/session-analytics-exports/download"].(map[string]any)
	require.True(t, ok)
	scheduledSessionAnalyticsGet, ok := scheduledSessionAnalyticsPath["get"].(map[string]any)
	require.True(t, ok)
	assert.Equal(t, "Download scheduled session analytics export", scheduledSessionAnalyticsGet["summary"])

	scheduledSessionPath, ok := paths["/api/v1/system/session-exports/download"].(map[string]any)
	require.True(t, ok)
	scheduledSessionGet, ok := scheduledSessionPath["get"].(map[string]any)
	require.True(t, ok)
	assert.Equal(t, "Download scheduled session export", scheduledSessionGet["summary"])

	components, ok := payload["components"].(map[string]any)
	require.True(t, ok)
	securitySchemes, ok := components["securitySchemes"].(map[string]any)
	require.True(t, ok)
	require.Contains(t, securitySchemes, "bearerAuth")
}
