package wireless

import (
	"fmt"
	"strings"

	"github.com/yourorg/aegisnas-pi4/internal/config"
)

// GenerateHostapdConfig renders a hostapd configuration for the configured
// radio and SSIDs. This is intended for physical appliance builds where a
// supported Wi-Fi interface is present.
func GenerateHostapdConfig(cfg *config.Config) (string, error) {
	if cfg == nil {
		return "", fmt.Errorf("config is required")
	}
	if !cfg.Wireless.Enabled {
		return "# hostapd.conf - wireless is disabled\n", nil
	}
	if err := cfg.Validate(); err != nil {
		return "", err
	}
	if len(cfg.Wireless.SSIDs) == 0 {
		return "", fmt.Errorf("wireless requires at least one SSID")
	}

	var lines []string
	lines = append(lines,
		"# hostapd.conf - generated by AegisNAS",
		fmt.Sprintf("interface=%s", cfg.Wireless.Interface),
		fmt.Sprintf("driver=%s", nonEmpty(cfg.Wireless.Driver, "nl80211")),
		fmt.Sprintf("ctrl_interface=%s", nonEmpty(cfg.Wireless.CtrlInterface, "/var/run/hostapd")),
		fmt.Sprintf("country_code=%s", strings.ToUpper(nonEmpty(cfg.Wireless.CountryCode, "US"))),
		fmt.Sprintf("hw_mode=%s", nonEmpty(cfg.Wireless.HWMode, "g")),
		fmt.Sprintf("channel=%d", cfg.Wireless.Channel),
		fmt.Sprintf("beacon_int=%d", max(cfg.Wireless.BeaconInterval, 100)),
		fmt.Sprintf("wmm_enabled=%d", boolAsInt(cfg.Wireless.WMMEnabled)),
		fmt.Sprintf("ieee80211n=%d", boolAsInt(cfg.Wireless.HTEnabled)),
	)

	for index, ssid := range cfg.Wireless.SSIDs {
		if index > 0 {
			lines = append(lines, fmt.Sprintf("bss=%s_%d", cfg.Wireless.Interface, index))
		}
		lines = append(lines, renderSSID(cfg, ssid)...)
	}

	lines = append(lines, "")
	return strings.Join(lines, "\n"), nil
}

func renderSSID(cfg *config.Config, ssid config.SSIDConfig) []string {
	lines := []string{
		"",
		fmt.Sprintf("ssid=%s", ssid.Name),
		fmt.Sprintf("ignore_broadcast_ssid=%d", boolAsInt(ssid.Hidden)),
		fmt.Sprintf("ap_isolate=%d", boolAsInt(ssid.ClientIsolation)),
	}
	if ssid.MaxClients > 0 {
		lines = append(lines, fmt.Sprintf("max_num_sta=%d", ssid.MaxClients))
	}
	if ssid.Bridge != "" {
		lines = append(lines, fmt.Sprintf("bridge=%s", ssid.Bridge))
	}
	if ssid.VLAN > 0 {
		lines = append(lines, fmt.Sprintf("# aegisnas_vlan=%d", ssid.VLAN))
	}
	if ssid.PortalProfile != "" {
		lines = append(lines, fmt.Sprintf("# aegisnas_portal_profile=%s", ssid.PortalProfile))
	}
	if ssid.IdentitySource != "" {
		lines = append(lines, fmt.Sprintf("# aegisnas_identity_source=%s", ssid.IdentitySource))
	}
	if ssid.BandwidthProfile != "" {
		lines = append(lines, fmt.Sprintf("# aegisnas_bandwidth_profile=%s", ssid.BandwidthProfile))
	}

	switch ssid.AuthMode {
	case "open":
		lines = append(lines, "auth_algs=1")
	case "captive-portal":
		lines = append(lines,
			"auth_algs=1",
			"# captive portal access is enforced by the AegisNAS gateway and portal services",
		)
	case "wpa2-personal":
		lines = append(lines,
			"wpa=2",
			"wpa_key_mgmt=WPA-PSK",
			"rsn_pairwise=CCMP",
			fmt.Sprintf("wpa_passphrase=%s", ssid.Passphrase),
		)
	case "wpa3-personal":
		lines = append(lines,
			"wpa=2",
			"wpa_key_mgmt=SAE",
			"rsn_pairwise=CCMP",
			"ieee80211w=2",
			"sae_require_mfp=1",
			fmt.Sprintf("sae_password=%s", ssid.Passphrase),
		)
	case "wpa2-enterprise":
		lines = append(lines,
			"ieee8021x=1",
			"wpa=2",
			"wpa_key_mgmt=WPA-EAP",
			"rsn_pairwise=CCMP",
			"auth_algs=1",
			"own_ip_addr=127.0.0.1",
			fmt.Sprintf("auth_server_addr=127.0.0.1"),
			fmt.Sprintf("auth_server_port=%d", cfg.Radius.AuthPort),
			fmt.Sprintf("auth_server_shared_secret=%s", cfg.Radius.Secret),
			fmt.Sprintf("acct_server_addr=127.0.0.1"),
			fmt.Sprintf("acct_server_port=%d", cfg.Radius.AcctPort),
			fmt.Sprintf("acct_server_shared_secret=%s", cfg.Radius.Secret),
		)
		if ssid.DynamicVLAN {
			lines = append(lines, "dynamic_vlan=1")
		}
	case "wpa3-enterprise":
		lines = append(lines,
			"ieee8021x=1",
			"wpa=2",
			"wpa_key_mgmt=WPA-EAP-SHA256",
			"rsn_pairwise=CCMP",
			"ieee80211w=2",
			"auth_algs=1",
			"own_ip_addr=127.0.0.1",
			fmt.Sprintf("auth_server_addr=127.0.0.1"),
			fmt.Sprintf("auth_server_port=%d", cfg.Radius.AuthPort),
			fmt.Sprintf("auth_server_shared_secret=%s", cfg.Radius.Secret),
			fmt.Sprintf("acct_server_addr=127.0.0.1"),
			fmt.Sprintf("acct_server_port=%d", cfg.Radius.AcctPort),
			fmt.Sprintf("acct_server_shared_secret=%s", cfg.Radius.Secret),
		)
		if ssid.DynamicVLAN {
			lines = append(lines, "dynamic_vlan=1")
		}
	}

	return lines
}

func boolAsInt(value bool) int {
	if value {
		return 1
	}
	return 0
}

func nonEmpty(value, fallback string) string {
	if strings.TrimSpace(value) == "" {
		return fallback
	}
	return value
}

func max(a, b int) int {
	if a > b {
		return a
	}
	return b
}
