package wireless

import (
	"context"
	"crypto/sha256"
	"encoding/hex"
	"fmt"
	"net"
	"path/filepath"
	"strings"

	"github.com/yourorg/aegisnas-pi4/internal/config"
	"github.com/yourorg/aegisnas-pi4/internal/secrets"
)

// GenerateHostapdConfig renders a hostapd configuration for the configured
// radio and SSIDs. This is intended for physical appliance builds where a
// supported Wi-Fi interface is present.
func GenerateHostapdConfig(cfg *config.Config) (string, error) {
	if cfg == nil {
		return "", fmt.Errorf("config is required")
	}
	if !cfg.Wireless.Enabled {
		return "# hostapd.conf - wireless is disabled\n", nil
	}
	if err := cfg.Validate(); err != nil {
		return "", err
	}
	if len(cfg.Wireless.SSIDs) == 0 {
		return "", fmt.Errorf("wireless requires at least one SSID")
	}

	var lines []string
	lines = append(lines,
		"# hostapd.conf - generated by AegisNAS",
		fmt.Sprintf("interface=%s", cfg.Wireless.Interface),
		fmt.Sprintf("driver=%s", nonEmpty(cfg.Wireless.Driver, "nl80211")),
		fmt.Sprintf("ctrl_interface=%s", nonEmpty(cfg.Wireless.CtrlInterface, "/var/run/hostapd")),
		fmt.Sprintf("country_code=%s", strings.ToUpper(nonEmpty(cfg.Wireless.CountryCode, "US"))),
		fmt.Sprintf("hw_mode=%s", nonEmpty(cfg.Wireless.HWMode, "g")),
		fmt.Sprintf("channel=%d", cfg.Wireless.Channel),
		fmt.Sprintf("beacon_int=%d", max(cfg.Wireless.BeaconInterval, 100)),
		fmt.Sprintf("wmm_enabled=%d", boolAsInt(cfg.Wireless.WMMEnabled)),
		fmt.Sprintf("ieee80211n=%d", boolAsInt(cfg.Wireless.HTEnabled)),
	)

	for index, ssid := range cfg.Wireless.SSIDs {
		if index > 0 {
			lines = append(lines, fmt.Sprintf("bss=%s_%d", cfg.Wireless.Interface, index))
		}
		lines = append(lines, renderSSID(cfg, ssid)...)
	}

	lines = append(lines, "")
	return strings.Join(lines, "\n"), nil
}

func renderSSID(cfg *config.Config, ssid config.SSIDConfig) []string {
	roaming, roamingActive := config.EffectiveSSIDRoamingProfile(cfg.Wireless, ssid)
	lines := []string{
		"",
		fmt.Sprintf("ssid=%s", ssid.Name),
		fmt.Sprintf("ignore_broadcast_ssid=%d", boolAsInt(ssid.Hidden)),
		fmt.Sprintf("ap_isolate=%d", boolAsInt(ssid.ClientIsolation)),
	}
	if ssid.MaxClients > 0 {
		lines = append(lines, fmt.Sprintf("max_num_sta=%d", ssid.MaxClients))
	}
	if ssid.Bridge != "" {
		lines = append(lines, fmt.Sprintf("bridge=%s", ssid.Bridge))
	}
	if ssid.VLAN > 0 {
		lines = append(lines, fmt.Sprintf("# aegisnas_vlan=%d", ssid.VLAN))
	}
	if ssid.PortalProfile != "" {
		lines = append(lines, fmt.Sprintf("# aegisnas_portal_profile=%s", ssid.PortalProfile))
	}
	if ssid.IdentitySource != "" {
		lines = append(lines, fmt.Sprintf("# aegisnas_identity_source=%s", ssid.IdentitySource))
	}
	if ssid.BandwidthProfile != "" {
		lines = append(lines, fmt.Sprintf("# aegisnas_bandwidth_profile=%s", ssid.BandwidthProfile))
	}

	switch ssid.AuthMode {
	case "open":
		lines = append(lines, "auth_algs=1")
	case "captive-portal":
		lines = append(lines,
			"auth_algs=1",
			"# captive portal access is enforced by the AegisNAS gateway and portal services",
		)
	case "wpa2-personal":
		lines = append(lines,
			"wpa=2",
			"wpa_key_mgmt="+hostapdKeyManagement(ssid.AuthMode, roaming, roamingActive),
			"rsn_pairwise=CCMP",
			fmt.Sprintf("wpa_passphrase=%s", ssid.Passphrase),
		)
		lines = append(lines, renderRoamingLines(cfg, ssid, roaming, roamingActive)...)
	case "wpa3-personal":
		lines = append(lines,
			"wpa=2",
			"wpa_key_mgmt="+hostapdKeyManagement(ssid.AuthMode, roaming, roamingActive),
			"rsn_pairwise=CCMP",
			"ieee80211w=2",
			"sae_require_mfp=1",
			fmt.Sprintf("sae_password=%s", ssid.Passphrase),
		)
		lines = append(lines, renderRoamingLines(cfg, ssid, roaming, roamingActive)...)
	case "wpa2-enterprise":
		lines = append(lines,
			"ieee8021x=1",
			"wpa=2",
			"wpa_key_mgmt="+hostapdKeyManagement(ssid.AuthMode, roaming, roamingActive),
			"rsn_pairwise=CCMP",
			"auth_algs=1",
			"own_ip_addr=127.0.0.1",
			fmt.Sprintf("auth_server_addr=127.0.0.1"),
			fmt.Sprintf("auth_server_port=%d", cfg.Radius.AuthPort),
			fmt.Sprintf("auth_server_shared_secret=%s", cfg.Radius.Secret),
			fmt.Sprintf("acct_server_addr=127.0.0.1"),
			fmt.Sprintf("acct_server_port=%d", cfg.Radius.AcctPort),
			fmt.Sprintf("acct_server_shared_secret=%s", cfg.Radius.Secret),
		)
		if ssid.DynamicVLAN {
			lines = append(lines,
				fmt.Sprintf("dynamic_vlan=%d", HostapdDynamicVLANMode(ssid)),
				fmt.Sprintf("vlan_file=%s", HostapdVLANFilePath(cfg)),
			)
		}
		lines = append(lines, renderRoamingLines(cfg, ssid, roaming, roamingActive)...)
	case "wpa3-enterprise":
		lines = append(lines,
			"ieee8021x=1",
			"wpa=2",
			"wpa_key_mgmt="+hostapdKeyManagement(ssid.AuthMode, roaming, roamingActive),
			"rsn_pairwise=CCMP",
			"ieee80211w=2",
			"auth_algs=1",
			"own_ip_addr=127.0.0.1",
			fmt.Sprintf("auth_server_addr=127.0.0.1"),
			fmt.Sprintf("auth_server_port=%d", cfg.Radius.AuthPort),
			fmt.Sprintf("auth_server_shared_secret=%s", cfg.Radius.Secret),
			fmt.Sprintf("acct_server_addr=127.0.0.1"),
			fmt.Sprintf("acct_server_port=%d", cfg.Radius.AcctPort),
			fmt.Sprintf("acct_server_shared_secret=%s", cfg.Radius.Secret),
		)
		if ssid.DynamicVLAN {
			lines = append(lines,
				fmt.Sprintf("dynamic_vlan=%d", HostapdDynamicVLANMode(ssid)),
				fmt.Sprintf("vlan_file=%s", HostapdVLANFilePath(cfg)),
			)
		}
		lines = append(lines, renderRoamingLines(cfg, ssid, roaming, roamingActive)...)
	}

	return lines
}

func hostapdKeyManagement(authMode string, roaming config.EffectiveWirelessRoamingProfile, roamingActive bool) string {
	ft := roamingActive && roaming.IEEE80211R
	switch strings.ToLower(strings.TrimSpace(authMode)) {
	case "wpa2-personal":
		if ft {
			return "WPA-PSK FT-PSK"
		}
		return "WPA-PSK"
	case "wpa3-personal":
		if ft {
			return "SAE FT-SAE"
		}
		return "SAE"
	case "wpa2-enterprise":
		if ft {
			return "WPA-EAP FT-EAP"
		}
		return "WPA-EAP"
	case "wpa3-enterprise":
		if ft {
			return "WPA-EAP-SHA256 FT-EAP"
		}
		return "WPA-EAP-SHA256"
	default:
		return ""
	}
}

func renderRoamingLines(cfg *config.Config, ssid config.SSIDConfig, roaming config.EffectiveWirelessRoamingProfile, active bool) []string {
	if cfg == nil || !active {
		return nil
	}
	var lines []string
	lines = append(lines, fmt.Sprintf("# aegisnas_roaming_profile=%s", roaming.ProfileName))
	if roaming.PMFRequired && (ssid.AuthMode == "wpa2-personal" || ssid.AuthMode == "wpa2-enterprise") {
		lines = append(lines, "ieee80211w=2")
	}
	if roaming.IEEE80211R {
		lines = append(lines,
			fmt.Sprintf("mobility_domain=%s", strings.ToLower(strings.TrimSpace(roaming.MobilityDomain))),
			fmt.Sprintf("ft_over_ds=%d", boolAsInt(roaming.FTOverDS)),
			fmt.Sprintf("r0_key_lifetime=%d", roaming.R0KeyLifetimeSeconds),
			fmt.Sprintf("reassociation_deadline=%d", roaming.ReassociationDeadline),
			fmt.Sprintf("nas_identifier=%s", roaming.NASIdentifier),
			fmt.Sprintf("r1_key_holder=%s", strings.ToLower(strings.TrimSpace(roaming.R1KeyHolder))),
			"pmk_r1_push=1",
		)
		if strings.Contains(strings.ToLower(ssid.AuthMode), "personal") {
			lines = append(lines, "ft_psk_generate_local=1")
		}
		lines = append(lines, renderFTNeighborKeys(cfg, ssid, roaming)...)
	}
	if roaming.IEEE80211K {
		if roaming.RRMNeighborReport {
			lines = append(lines, "rrm_neighbor_report=1")
		}
		if roaming.RRMBeaconReport {
			lines = append(lines, "rrm_beacon_report=1")
		}
	}
	if roaming.IEEE80211V {
		if roaming.BSSTransition {
			lines = append(lines, "bss_transition=1")
		}
		if roaming.WNMSleepMode {
			lines = append(lines, "wnm_sleep_mode=1")
		}
	}
	return lines
}

func renderFTNeighborKeys(cfg *config.Config, ssid config.SSIDConfig, roaming config.EffectiveWirelessRoamingProfile) []string {
	if len(roaming.NeighborAPs) == 0 {
		return nil
	}
	var lines []string
	resolver := secrets.NewResolver(secrets.OptionsFromConfig(cfg))
	for _, neighbor := range roaming.NeighborAPs {
		ref := strings.TrimSpace(neighbor.KeySeedRef)
		if ref == "" {
			ref = strings.TrimSpace(roaming.KeySeedRef)
		}
		if ref == "" {
			lines = append(lines, fmt.Sprintf("# aegisnas_roaming_neighbor=%s missing_key_seed_ref", firstNonEmpty(neighbor.Name, neighbor.BSSID)))
			continue
		}
		seed, err := resolver.Resolve(context.Background(), ref)
		if err != nil {
			lines = append(lines, fmt.Sprintf("# aegisnas_roaming_neighbor=%s key_seed_ref_unavailable:%s", firstNonEmpty(neighbor.Name, neighbor.BSSID), sanitizeInlineComment(err.Error())))
			continue
		}
		bssid := normalizeHostapdMAC(neighbor.BSSID)
		r1KeyHolder := strings.ToLower(strings.ReplaceAll(strings.ReplaceAll(strings.TrimSpace(neighbor.R1KeyHolder), ":", ""), "-", ""))
		if r1KeyHolder == "" {
			r1KeyHolder = strings.ToLower(strings.TrimSpace(roaming.R1KeyHolder))
		}
		nasID := strings.TrimSpace(neighbor.NASIdentifier)
		if nasID == "" {
			nasID = firstNonEmpty(neighbor.Name, bssid)
		}
		key := deriveFTNeighborKey(seed, roaming.ProfileName, ssid.Name, bssid, r1KeyHolder)
		lines = append(lines,
			fmt.Sprintf("r0kh=%s %s %s", bssid, nasID, key),
			fmt.Sprintf("r1kh=%s %s %s", bssid, r1KeyHolder, key),
		)
	}
	return lines
}

func deriveFTNeighborKey(seed, profileName, ssidName, bssid, r1KeyHolder string) string {
	raw := strings.Join([]string{
		"aegisnas-hostapd-ft",
		seed,
		strings.TrimSpace(profileName),
		strings.TrimSpace(ssidName),
		strings.ToLower(strings.TrimSpace(bssid)),
		strings.ToLower(strings.TrimSpace(r1KeyHolder)),
	}, "\x00")
	sum := sha256.Sum256([]byte(raw))
	return hex.EncodeToString(sum[:])[:32]
}

func normalizeHostapdMAC(value string) string {
	mac, err := net.ParseMAC(strings.TrimSpace(value))
	if err != nil || len(mac) != 6 {
		return strings.ToLower(strings.TrimSpace(value))
	}
	parts := make([]string, 0, 6)
	for _, octet := range mac {
		parts = append(parts, fmt.Sprintf("%02x", octet))
	}
	return strings.Join(parts, ":")
}

func sanitizeInlineComment(value string) string {
	value = strings.ReplaceAll(value, "\r", " ")
	value = strings.ReplaceAll(value, "\n", " ")
	value = strings.ReplaceAll(value, "\t", " ")
	if len(value) > 96 {
		return value[:96]
	}
	return value
}

func HostapdVLANFilePath(cfg *config.Config) string {
	if cfg == nil {
		return "/etc/hostapd/aegisnas-vlans.conf"
	}
	if path := strings.TrimSpace(cfg.Wireless.HostapdVLANFilePath); path != "" {
		return path
	}
	if configPath := strings.TrimSpace(cfg.Wireless.HostapdConfigPath); configPath != "" {
		return filepath.Join(filepath.Dir(configPath), "aegisnas-vlans.conf")
	}
	return "/etc/hostapd/aegisnas-vlans.conf"
}

func HostapdWirelessVLANInterface(wirelessInterface string, vlan int) string {
	wirelessInterface = strings.TrimSpace(wirelessInterface)
	if wirelessInterface == "" || vlan <= 0 {
		return ""
	}
	return fmt.Sprintf("%s.%d", wirelessInterface, vlan)
}

func HostapdDynamicVLANMode(ssid config.SSIDConfig) int {
	if !ssid.DynamicVLAN {
		return 0
	}
	if ssid.VLAN > 0 {
		return 1
	}
	return 2
}

func boolAsInt(value bool) int {
	if value {
		return 1
	}
	return 0
}

func nonEmpty(value, fallback string) string {
	if strings.TrimSpace(value) == "" {
		return fallback
	}
	return value
}

func firstNonEmpty(values ...string) string {
	for _, value := range values {
		if strings.TrimSpace(value) != "" {
			return value
		}
	}
	return ""
}

func max(a, b int) int {
	if a > b {
		return a
	}
	return b
}
