package wireless

import (
	"context"
	"crypto/sha256"
	"encoding/hex"
	"fmt"
	"net"
	"path/filepath"
	"strings"

	"github.com/yourorg/aegisnas-pi4/internal/config"
	"github.com/yourorg/aegisnas-pi4/internal/secrets"
)

// GenerateHostapdConfig renders a hostapd configuration for the configured
// radio and SSIDs. This is intended for physical appliance builds where a
// supported Wi-Fi interface is present.
func GenerateHostapdConfig(cfg *config.Config) (string, error) {
	if cfg == nil {
		return "", fmt.Errorf("config is required")
	}
	if !cfg.Wireless.Enabled {
		return "# hostapd.conf - wireless is disabled\n", nil
	}
	if err := cfg.Validate(); err != nil {
		return "", err
	}
	if len(cfg.Wireless.SSIDs) == 0 {
		return "", fmt.Errorf("wireless requires at least one SSID")
	}

	var lines []string
	lines = append(lines,
		"# hostapd.conf - generated by AegisNAS",
		fmt.Sprintf("interface=%s", cfg.Wireless.Interface),
		fmt.Sprintf("driver=%s", nonEmpty(cfg.Wireless.Driver, "nl80211")),
		fmt.Sprintf("ctrl_interface=%s", nonEmpty(cfg.Wireless.CtrlInterface, "/var/run/hostapd")),
		fmt.Sprintf("country_code=%s", strings.ToUpper(nonEmpty(cfg.Wireless.CountryCode, "US"))),
		fmt.Sprintf("hw_mode=%s", nonEmpty(cfg.Wireless.HWMode, "g")),
		fmt.Sprintf("channel=%d", cfg.Wireless.Channel),
		fmt.Sprintf("beacon_int=%d", max(cfg.Wireless.BeaconInterval, 100)),
		fmt.Sprintf("wmm_enabled=%d", boolAsInt(cfg.Wireless.WMMEnabled)),
		fmt.Sprintf("ieee80211n=%d", boolAsInt(cfg.Wireless.HTEnabled)),
	)

	for index, ssid := range cfg.Wireless.SSIDs {
		if index > 0 {
			lines = append(lines, fmt.Sprintf("bss=%s_%d", cfg.Wireless.Interface, index))
		}
		lines = append(lines, renderSSID(cfg, ssid)...)
	}

	lines = append(lines, "")
	return strings.Join(lines, "\n"), nil
}

func renderSSID(cfg *config.Config, ssid config.SSIDConfig) []string {
	roaming, roamingActive := config.EffectiveSSIDRoamingProfile(cfg.Wireless, ssid)
	passpoint, passpointActive := config.EffectiveSSIDPasspointProfile(cfg.Wireless, ssid)
	lines := []string{
		"",
		fmt.Sprintf("ssid=%s", ssid.Name),
		fmt.Sprintf("ignore_broadcast_ssid=%d", boolAsInt(ssid.Hidden)),
		fmt.Sprintf("ap_isolate=%d", boolAsInt(ssid.ClientIsolation)),
	}
	if ssid.MaxClients > 0 {
		lines = append(lines, fmt.Sprintf("max_num_sta=%d", ssid.MaxClients))
	}
	if ssid.Bridge != "" {
		lines = append(lines, fmt.Sprintf("bridge=%s", ssid.Bridge))
	}
	if ssid.VLAN > 0 {
		lines = append(lines, fmt.Sprintf("# aegisnas_vlan=%d", ssid.VLAN))
	}
	if ssid.PortalProfile != "" {
		lines = append(lines, fmt.Sprintf("# aegisnas_portal_profile=%s", ssid.PortalProfile))
	}
	if ssid.IdentitySource != "" {
		lines = append(lines, fmt.Sprintf("# aegisnas_identity_source=%s", ssid.IdentitySource))
	}
	if ssid.BandwidthProfile != "" {
		lines = append(lines, fmt.Sprintf("# aegisnas_bandwidth_profile=%s", ssid.BandwidthProfile))
	}

	switch ssid.AuthMode {
	case "open":
		lines = append(lines, "auth_algs=1")
	case "captive-portal":
		lines = append(lines,
			"auth_algs=1",
			"# captive portal access is enforced by the AegisNAS gateway and portal services",
		)
	case "wpa2-personal":
		lines = append(lines,
			"wpa=2",
			"wpa_key_mgmt="+hostapdKeyManagement(ssid.AuthMode, roaming, roamingActive),
			"rsn_pairwise=CCMP",
			fmt.Sprintf("wpa_passphrase=%s", ssid.Passphrase),
		)
		lines = append(lines, renderRoamingLines(cfg, ssid, roaming, roamingActive)...)
	case "wpa3-personal":
		lines = append(lines,
			"wpa=2",
			"wpa_key_mgmt="+hostapdKeyManagement(ssid.AuthMode, roaming, roamingActive),
			"rsn_pairwise=CCMP",
			"ieee80211w=2",
			"sae_require_mfp=1",
			fmt.Sprintf("sae_password=%s", ssid.Passphrase),
		)
		lines = append(lines, renderRoamingLines(cfg, ssid, roaming, roamingActive)...)
	case "wpa2-enterprise":
		lines = append(lines,
			"ieee8021x=1",
			"wpa=2",
			"wpa_key_mgmt="+hostapdKeyManagement(ssid.AuthMode, roaming, roamingActive),
			"rsn_pairwise=CCMP",
			"auth_algs=1",
			"own_ip_addr=127.0.0.1",
			fmt.Sprintf("auth_server_addr=127.0.0.1"),
			fmt.Sprintf("auth_server_port=%d", cfg.Radius.AuthPort),
			fmt.Sprintf("auth_server_shared_secret=%s", cfg.Radius.Secret),
			fmt.Sprintf("acct_server_addr=127.0.0.1"),
			fmt.Sprintf("acct_server_port=%d", cfg.Radius.AcctPort),
			fmt.Sprintf("acct_server_shared_secret=%s", cfg.Radius.Secret),
		)
		if ssid.DynamicVLAN {
			lines = append(lines,
				fmt.Sprintf("dynamic_vlan=%d", HostapdDynamicVLANMode(ssid)),
				fmt.Sprintf("vlan_file=%s", HostapdVLANFilePath(cfg)),
			)
		}
		lines = append(lines, renderRoamingLines(cfg, ssid, roaming, roamingActive)...)
	case "wpa3-enterprise":
		lines = append(lines,
			"ieee8021x=1",
			"wpa=2",
			"wpa_key_mgmt="+hostapdKeyManagement(ssid.AuthMode, roaming, roamingActive),
			"rsn_pairwise=CCMP",
			"ieee80211w=2",
			"auth_algs=1",
			"own_ip_addr=127.0.0.1",
			fmt.Sprintf("auth_server_addr=127.0.0.1"),
			fmt.Sprintf("auth_server_port=%d", cfg.Radius.AuthPort),
			fmt.Sprintf("auth_server_shared_secret=%s", cfg.Radius.Secret),
			fmt.Sprintf("acct_server_addr=127.0.0.1"),
			fmt.Sprintf("acct_server_port=%d", cfg.Radius.AcctPort),
			fmt.Sprintf("acct_server_shared_secret=%s", cfg.Radius.Secret),
		)
		if ssid.DynamicVLAN {
			lines = append(lines,
				fmt.Sprintf("dynamic_vlan=%d", HostapdDynamicVLANMode(ssid)),
				fmt.Sprintf("vlan_file=%s", HostapdVLANFilePath(cfg)),
			)
		}
		lines = append(lines, renderRoamingLines(cfg, ssid, roaming, roamingActive)...)
	}

	lines = append(lines, renderPasspointLines(ssid, passpoint, passpointActive)...)
	return lines
}

func hostapdKeyManagement(authMode string, roaming config.EffectiveWirelessRoamingProfile, roamingActive bool) string {
	ft := roamingActive && roaming.IEEE80211R
	switch strings.ToLower(strings.TrimSpace(authMode)) {
	case "wpa2-personal":
		if ft {
			return "WPA-PSK FT-PSK"
		}
		return "WPA-PSK"
	case "wpa3-personal":
		if ft {
			return "SAE FT-SAE"
		}
		return "SAE"
	case "wpa2-enterprise":
		if ft {
			return "WPA-EAP FT-EAP"
		}
		return "WPA-EAP"
	case "wpa3-enterprise":
		if ft {
			return "WPA-EAP-SHA256 FT-EAP"
		}
		return "WPA-EAP-SHA256"
	default:
		return ""
	}
}

func renderRoamingLines(cfg *config.Config, ssid config.SSIDConfig, roaming config.EffectiveWirelessRoamingProfile, active bool) []string {
	if cfg == nil || !active {
		return nil
	}
	var lines []string
	lines = append(lines, fmt.Sprintf("# aegisnas_roaming_profile=%s", roaming.ProfileName))
	if roaming.PMFRequired && (ssid.AuthMode == "wpa2-personal" || ssid.AuthMode == "wpa2-enterprise") {
		lines = append(lines, "ieee80211w=2")
	}
	if roaming.IEEE80211R {
		lines = append(lines,
			fmt.Sprintf("mobility_domain=%s", strings.ToLower(strings.TrimSpace(roaming.MobilityDomain))),
			fmt.Sprintf("ft_over_ds=%d", boolAsInt(roaming.FTOverDS)),
			fmt.Sprintf("r0_key_lifetime=%d", roaming.R0KeyLifetimeSeconds),
			fmt.Sprintf("reassociation_deadline=%d", roaming.ReassociationDeadline),
			fmt.Sprintf("nas_identifier=%s", roaming.NASIdentifier),
			fmt.Sprintf("r1_key_holder=%s", strings.ToLower(strings.TrimSpace(roaming.R1KeyHolder))),
			"pmk_r1_push=1",
		)
		if strings.Contains(strings.ToLower(ssid.AuthMode), "personal") {
			lines = append(lines, "ft_psk_generate_local=1")
		}
		lines = append(lines, renderFTNeighborKeys(cfg, ssid, roaming)...)
	}
	if roaming.IEEE80211K {
		if roaming.RRMNeighborReport {
			lines = append(lines, "rrm_neighbor_report=1")
		}
		if roaming.RRMBeaconReport {
			lines = append(lines, "rrm_beacon_report=1")
		}
	}
	if roaming.IEEE80211V {
		if roaming.BSSTransition {
			lines = append(lines, "bss_transition=1")
		}
		if roaming.WNMSleepMode {
			lines = append(lines, "wnm_sleep_mode=1")
		}
	}
	return lines
}

func renderFTNeighborKeys(cfg *config.Config, ssid config.SSIDConfig, roaming config.EffectiveWirelessRoamingProfile) []string {
	if len(roaming.NeighborAPs) == 0 {
		return nil
	}
	var lines []string
	resolver := secrets.NewResolver(secrets.OptionsFromConfig(cfg))
	for _, neighbor := range roaming.NeighborAPs {
		ref := strings.TrimSpace(neighbor.KeySeedRef)
		if ref == "" {
			ref = strings.TrimSpace(roaming.KeySeedRef)
		}
		if ref == "" {
			lines = append(lines, fmt.Sprintf("# aegisnas_roaming_neighbor=%s missing_key_seed_ref", firstNonEmpty(neighbor.Name, neighbor.BSSID)))
			continue
		}
		seed, err := resolver.Resolve(context.Background(), ref)
		if err != nil {
			lines = append(lines, fmt.Sprintf("# aegisnas_roaming_neighbor=%s key_seed_ref_unavailable:%s", firstNonEmpty(neighbor.Name, neighbor.BSSID), sanitizeInlineComment(err.Error())))
			continue
		}
		bssid := normalizeHostapdMAC(neighbor.BSSID)
		r1KeyHolder := strings.ToLower(strings.ReplaceAll(strings.ReplaceAll(strings.TrimSpace(neighbor.R1KeyHolder), ":", ""), "-", ""))
		if r1KeyHolder == "" {
			r1KeyHolder = strings.ToLower(strings.TrimSpace(roaming.R1KeyHolder))
		}
		nasID := strings.TrimSpace(neighbor.NASIdentifier)
		if nasID == "" {
			nasID = firstNonEmpty(neighbor.Name, bssid)
		}
		key := deriveFTNeighborKey(seed, roaming.ProfileName, ssid.Name, bssid, r1KeyHolder)
		lines = append(lines,
			fmt.Sprintf("r0kh=%s %s %s", bssid, nasID, key),
			fmt.Sprintf("r1kh=%s %s %s", bssid, r1KeyHolder, key),
		)
	}
	return lines
}

func renderPasspointLines(ssid config.SSIDConfig, passpoint config.EffectiveWirelessPasspointProfile, active bool) []string {
	if !active {
		return nil
	}
	lines := []string{
		fmt.Sprintf("# aegisnas_passpoint_profile=%s", sanitizeHostapdValue(passpoint.ProfileName)),
	}
	if passpoint.Interworking {
		lines = append(lines,
			"interworking=1",
			fmt.Sprintf("access_network_type=%d", passpoint.AccessNetworkType),
			fmt.Sprintf("internet=%d", boolAsInt(passpoint.Internet)),
			fmt.Sprintf("asra=%d", boolAsInt(passpoint.ASRA)),
			fmt.Sprintf("esr=%d", boolAsInt(passpoint.ESR)),
			fmt.Sprintf("uesa=%d", boolAsInt(passpoint.UESA)),
		)
		if passpoint.VenueGroup > 0 {
			lines = append(lines, fmt.Sprintf("venue_group=%d", passpoint.VenueGroup))
		}
		if passpoint.VenueType > 0 {
			lines = append(lines, fmt.Sprintf("venue_type=%d", passpoint.VenueType))
		}
		if strings.TrimSpace(passpoint.HESSID) != "" {
			lines = append(lines, fmt.Sprintf("hessid=%s", strings.ToLower(strings.TrimSpace(passpoint.HESSID))))
		}
		lines = append(lines, renderPasspointLocalizedLines("venue_name", passpoint.VenueNames)...)
		if len(passpoint.DomainNames) > 0 {
			lines = append(lines, "domain_name="+strings.Join(sanitizeHostapdList(passpoint.DomainNames), ","))
		}
		for _, oi := range sanitizeHostapdList(passpoint.RoamingConsortiumOIs) {
			lines = append(lines, "roaming_consortium="+strings.ToLower(oi))
		}
		for _, realm := range passpoint.NAIRealms {
			lines = append(lines, renderPasspointNAIRealm(realm))
		}
		if len(passpoint.CellularNetworks) > 0 {
			lines = append(lines, "anqp_3gpp_cell_net="+renderPasspointCellularNetworks(passpoint.CellularNetworks))
		}
	}
	if passpoint.HS20 {
		lines = append(lines,
			"hs20=1",
			fmt.Sprintf("disable_dgaf=%d", boolAsInt(passpoint.DisableDGAF)),
			fmt.Sprintf("proxy_arp=%d", boolAsInt(passpoint.ProxyARP)),
		)
		lines = append(lines, renderPasspointLocalizedLines("hs20_oper_friendly_name", passpoint.OperatorFriendlyNames)...)
		if passpoint.WANMetrics.Enabled {
			lines = append(lines, "hs20_wan_metrics="+renderPasspointWANMetrics(passpoint.WANMetrics))
		}
		for _, capability := range passpoint.ConnectionCapabilities {
			lines = append(lines, fmt.Sprintf("hs20_conn_capab=%d:%d:%d", capability.Protocol, capability.Port, capability.Status))
		}
		if passpoint.OSU.Enabled {
			osuSSID := strings.TrimSpace(passpoint.OSU.SSID)
			if osuSSID == "" {
				osuSSID = ssid.Name
			}
			lines = append(lines,
				"osu_ssid="+sanitizeHostapdValue(osuSSID),
				"osu_server_uri="+sanitizeHostapdValue(passpoint.OSU.ServerURI),
			)
			lines = append(lines, renderPasspointLocalizedLines("osu_friendly_name", passpoint.OSU.FriendlyNames)...)
			if strings.TrimSpace(passpoint.OSU.NAI) != "" {
				lines = append(lines, "osu_nai="+sanitizeHostapdValue(passpoint.OSU.NAI))
			}
			lines = append(lines, "osu_method_list="+renderPasspointOSUMethods(passpoint.OSU.MethodList))
			lines = append(lines, renderPasspointLocalizedLines("osu_service_desc", passpoint.OSU.ServiceDescriptions)...)
		}
	}
	return lines
}

func renderPasspointLocalizedLines(key string, values []config.WirelessLocalizedTextConfig) []string {
	lines := make([]string, 0, len(values))
	for _, value := range values {
		language := strings.ToLower(strings.TrimSpace(value.Language))
		text := sanitizeHostapdValue(value.Text)
		if language == "" || text == "" {
			continue
		}
		lines = append(lines, fmt.Sprintf("%s=%s:%s", key, language, text))
	}
	return lines
}

func renderPasspointNAIRealm(realm config.WirelessPasspointNAIRealmConfig) string {
	parts := []string{
		fmt.Sprintf("%d", realm.Encoding),
		sanitizeHostapdValue(realm.Realm),
	}
	authParams := sanitizeHostapdList(realm.AuthParams)
	for _, method := range realm.EAPMethods {
		eapID, ok := passpointEAPMethodID(method)
		if !ok {
			continue
		}
		rendered := fmt.Sprintf("%d", eapID)
		for _, param := range authParams {
			rendered += "[" + param + "]"
		}
		parts = append(parts, rendered)
	}
	return "nai_realm=" + strings.Join(parts, ",")
}

func passpointEAPMethodID(method string) (int, bool) {
	switch strings.ToLower(strings.TrimSpace(method)) {
	case "tls":
		return 13, true
	case "sim":
		return 18, true
	case "ttls":
		return 21, true
	case "aka":
		return 23, true
	case "peap":
		return 25, true
	case "fast":
		return 43, true
	case "aka-prime":
		return 50, true
	case "pwd":
		return 52, true
	case "teap":
		return 55, true
	default:
		return 0, false
	}
}

func renderPasspointCellularNetworks(networks []config.WirelessPasspointCellularNetworkConfig) string {
	parts := make([]string, 0, len(networks))
	for _, network := range networks {
		parts = append(parts, fmt.Sprintf("%s,%s", strings.TrimSpace(network.MCC), strings.TrimSpace(network.MNC)))
	}
	return strings.Join(parts, ";")
}

func renderPasspointWANMetrics(metrics config.WirelessPasspointWANMetricsConfig) string {
	wanInfo := strings.TrimSpace(metrics.WANInfo)
	if wanInfo == "" {
		wanInfo = "01"
	}
	if parsed, err := parseHostapdByte(wanInfo); err == nil {
		wanInfo = fmt.Sprintf("%02x", parsed)
	}
	return fmt.Sprintf("%s:%d:%d:%d:%d:%d", wanInfo, metrics.DownlinkKbps, metrics.UplinkKbps, metrics.DownlinkLoad, metrics.UplinkLoad, metrics.LMD)
}

func renderPasspointOSUMethods(values []int) string {
	if len(values) == 0 {
		return ""
	}
	parts := make([]string, 0, len(values))
	for _, value := range values {
		parts = append(parts, fmt.Sprintf("%d", value))
	}
	return strings.Join(parts, " ")
}

func sanitizeHostapdList(values []string) []string {
	items := make([]string, 0, len(values))
	for _, value := range values {
		value = sanitizeHostapdValue(value)
		if value == "" {
			continue
		}
		items = append(items, value)
	}
	return items
}

func sanitizeHostapdValue(value string) string {
	value = strings.TrimSpace(value)
	value = strings.ReplaceAll(value, "\r", " ")
	value = strings.ReplaceAll(value, "\n", " ")
	value = strings.ReplaceAll(value, "\t", " ")
	return value
}

func parseHostapdByte(value string) (int, error) {
	value = strings.TrimSpace(value)
	if len(value) == 2 {
		var parsed int
		_, err := fmt.Sscanf(value, "%02x", &parsed)
		if err == nil && parsed >= 0 && parsed <= 255 {
			return parsed, nil
		}
	}
	var parsed int
	_, err := fmt.Sscanf(value, "%d", &parsed)
	if err != nil || parsed < 0 || parsed > 255 {
		return 0, fmt.Errorf("invalid byte")
	}
	return parsed, nil
}

func deriveFTNeighborKey(seed, profileName, ssidName, bssid, r1KeyHolder string) string {
	raw := strings.Join([]string{
		"aegisnas-hostapd-ft",
		seed,
		strings.TrimSpace(profileName),
		strings.TrimSpace(ssidName),
		strings.ToLower(strings.TrimSpace(bssid)),
		strings.ToLower(strings.TrimSpace(r1KeyHolder)),
	}, "\x00")
	sum := sha256.Sum256([]byte(raw))
	return hex.EncodeToString(sum[:])[:32]
}

func normalizeHostapdMAC(value string) string {
	mac, err := net.ParseMAC(strings.TrimSpace(value))
	if err != nil || len(mac) != 6 {
		return strings.ToLower(strings.TrimSpace(value))
	}
	parts := make([]string, 0, 6)
	for _, octet := range mac {
		parts = append(parts, fmt.Sprintf("%02x", octet))
	}
	return strings.Join(parts, ":")
}

func sanitizeInlineComment(value string) string {
	value = strings.ReplaceAll(value, "\r", " ")
	value = strings.ReplaceAll(value, "\n", " ")
	value = strings.ReplaceAll(value, "\t", " ")
	if len(value) > 96 {
		return value[:96]
	}
	return value
}

func HostapdVLANFilePath(cfg *config.Config) string {
	if cfg == nil {
		return "/etc/hostapd/aegisnas-vlans.conf"
	}
	if path := strings.TrimSpace(cfg.Wireless.HostapdVLANFilePath); path != "" {
		return path
	}
	if configPath := strings.TrimSpace(cfg.Wireless.HostapdConfigPath); configPath != "" {
		return filepath.Join(filepath.Dir(configPath), "aegisnas-vlans.conf")
	}
	return "/etc/hostapd/aegisnas-vlans.conf"
}

func HostapdWirelessVLANInterface(wirelessInterface string, vlan int) string {
	wirelessInterface = strings.TrimSpace(wirelessInterface)
	if wirelessInterface == "" || vlan <= 0 {
		return ""
	}
	return fmt.Sprintf("%s.%d", wirelessInterface, vlan)
}

func HostapdDynamicVLANMode(ssid config.SSIDConfig) int {
	if !ssid.DynamicVLAN {
		return 0
	}
	if ssid.VLAN > 0 {
		return 1
	}
	return 2
}

func boolAsInt(value bool) int {
	if value {
		return 1
	}
	return 0
}

func nonEmpty(value, fallback string) string {
	if strings.TrimSpace(value) == "" {
		return fallback
	}
	return value
}

func firstNonEmpty(values ...string) string {
	for _, value := range values {
		if strings.TrimSpace(value) != "" {
			return value
		}
	}
	return ""
}

func max(a, b int) int {
	if a > b {
		return a
	}
	return b
}
