package radius

import (
	"bytes"
	"strings"
	"text/template"

	"github.com/yourorg/aegisnas-pi4/internal/config"
)

// GenerateEAPConfig creates the eap module configuration for FreeRADIUS.
func GenerateEAPConfig(cfg *config.Config, certDir string) (string, error) {
	tmpl := `# -*- text -*-
# eap.conf – generated by aegis-radius
eap {
	default_eap_type = {{ .DefaultType }}
	timer_expire = 60
	ignore_unknown_eap_types = no
	cisco_accounting_username_bug = no
	max_sessions = {{ .MaxSessions }}

	tls-config tls-common {
		private_key_file = {{ .CertDir }}/server.key
		certificate_file = {{ .CertDir }}/server.crt
		ca_file = {{ .CertDir }}/ca.crt
		dh_file = {{ .CertDir }}/dh
		random_file = /dev/urandom
		fragment_size = 1024
		include_length = yes
		auto_chain = yes
		check_crl = {{ .CheckCRL }}
		check_all_crl = {{ .CheckAllCRL }}
{{ if .CheckCRL }}
		ca_path = {{ .CertDir }}
		ca_path_reload_interval = {{ .CAPathReloadInterval }}
{{ end }}
		cipher_list = "DEFAULT"
		ecdh_curve = "prime256v1"
		tls_min_version = "{{ .TLSMinVersion }}"
		tls_max_version = "{{ .TLSMaxVersion }}"

		verify {
			skip_if_ocsp_ok = no
		}

		ocsp {
			enable = {{ .OCSPEnabled }}
			override_cert_url = {{ .OCSPOverrideCertURL }}
{{ if .OCSPURL }}
			url = "{{ .OCSPURL }}"
{{ end }}
			use_nonce = {{ .OCSPUseNonce }}
			timeout = {{ .OCSPTimeoutSeconds }}
			softfail = {{ .OCSPSoftFail }}
		}
	}

	peap {
		default_eap_type = {{ .PEAPInner }}
		tls = tls-common
		copy_request_to_tunnel = no
		use_tunneled_reply = no
		proxy_tunneled_request_as_eap = yes
		virtual_server = "inner-tunnel"
	}

	ttls {
		default_eap_type = {{ .TTLSInner }}
		tls = tls-common
		copy_request_to_tunnel = no
		use_tunneled_reply = no
		virtual_server = "inner-tunnel"
	}

	tls {
		tls = tls-common
		virtual_server = "inner-tunnel"
	}

	mschapv2 {
		with_ntdomain_hack = no
		send_error = yes
	}
}
`
	data := struct {
		MaxSessions          int
		CertDir              string
		DefaultType          string
		PEAPInner            string
		TTLSInner            string
		TLSMinVersion        string
		TLSMaxVersion        string
		CheckCRL             string
		CheckAllCRL          string
		CAPathReloadInterval int
		OCSPEnabled          string
		OCSPOverrideCertURL  string
		OCSPURL              string
		OCSPUseNonce         string
		OCSPTimeoutSeconds   int
		OCSPSoftFail         string
	}{
		MaxSessions:          cfg.Radius.MaxSessions,
		CertDir:              certDir,
		DefaultType:          cfg.Radius.EAP.DefaultType,
		PEAPInner:            cfg.Radius.EAP.PEAPInner,
		TTLSInner:            cfg.Radius.EAP.TTLSInner,
		TLSMinVersion:        cfg.Radius.EAP.TLSMinVersion,
		TLSMaxVersion:        cfg.Radius.EAP.TLSMaxVersion,
		CheckCRL:             radiusYesNo(cfg.Radius.EAP.CheckCRL),
		CheckAllCRL:          radiusYesNo(cfg.Radius.EAP.CheckAllCRL),
		CAPathReloadInterval: cfg.Radius.EAP.CAPathReloadInterval,
		OCSPEnabled:          radiusYesNo(cfg.Radius.EAP.OCSP.Enabled),
		OCSPOverrideCertURL:  radiusYesNo(cfg.Radius.EAP.OCSP.OverrideCertURL),
		OCSPURL:              strings.TrimSpace(cfg.Radius.EAP.OCSP.URL),
		OCSPUseNonce:         radiusYesNo(cfg.Radius.EAP.OCSP.UseNonce),
		OCSPTimeoutSeconds:   cfg.Radius.EAP.OCSP.TimeoutSeconds,
		OCSPSoftFail:         radiusYesNo(cfg.Radius.EAP.OCSP.SoftFail),
	}
	var buf bytes.Buffer
	t := template.Must(template.New("eap").Parse(tmpl))
	err := t.Execute(&buf, data)
	return buf.String(), err
}

func radiusYesNo(value bool) string {
	if value {
		return "yes"
	}
	return "no"
}
