package radius

import (
	"bytes"
	"fmt"
	"strings"
	"text/template"

	"github.com/yourorg/aegisnas-pi4/internal/config"
	eappkg "github.com/yourorg/aegisnas-pi4/internal/eap"
)

// GenerateEAPConfig creates the eap module configuration for FreeRADIUS.
func GenerateEAPConfig(cfg *config.Config, certDir string) (string, error) {
	frameworkReport := eappkg.BuildFrameworkReport(cfg, eappkg.RuntimeSummary{})
	framework := frameworkReport.Policy
	teapPolicy := eappkg.BuildTEAPPolicyReport(cfg)
	fastPolicy := eappkg.BuildFASTPolicyReport(cfg)
	pwdPolicy := eappkg.BuildPWDPolicyReport(cfg)
	simAKAPolicy := eappkg.BuildSIMAKAPolicyReport(cfg)
	if frameworkReport.Status == "blocked" && framework.Mode == "enforce" && framework.FailClosed {
		return "", fmt.Errorf("EAP framework blocked FreeRADIUS generation: %s", strings.Join(frameworkReport.BlockingIssues, "; "))
	}
	tmpl := `# -*- text -*-
# eap.conf - generated by aegis-radius
# NAS-0022 EAP framework status: {{ .FrameworkStatus }}
# EAP framework mode: {{ .FrameworkMode }}, fail_closed={{ .FrameworkFailClosed }}
# Allowed outer methods: {{ .AllowedMethods }}
# Allowed inner methods: {{ .AllowedInnerMethods }}
# NAS-0023 TEAP generated: {{ .TEAPEnabled }}, chain_mode={{ .TEAPChainMode }}, cryptobinding={{ .TEAPRequireCryptoBinding }}, channel_binding={{ .TEAPRequireChannelBinding }}
# NAS-0024 EAP-FAST generated: {{ .FASTEnabled }}, pac={{ .FASTAllowPAC }}, cryptobinding={{ .FASTRequireCryptoBinding }}
# NAS-0024 EAP-PWD generated: {{ .PWDEnabled }}, group={{ .PWDGroup }}, source={{ .PWDPasswordSource }}
# NAS-0025 EAP-SIM/AKA generated: {{ .SIMAKAEnabled }}, methods={{ .SIMAKAMethods }}, vector_provider={{ .SIMAKAVectorProvider }}, fresh_vectors={{ .SIMAKARequireFreshVectors }}
eap {
	default_eap_type = {{ .DefaultType }}
	timer_expire = {{ .MethodTimeoutSeconds }}
	ignore_unknown_eap_types = no
	cisco_accounting_username_bug = no
	max_sessions = {{ .MaxSessions }}

	tls-config tls-common {
		private_key_file = {{ .CertDir }}/server.key
		certificate_file = {{ .CertDir }}/server.crt
		ca_file = {{ .CertDir }}/ca.crt
		dh_file = {{ .CertDir }}/dh
		random_file = /dev/urandom
		fragment_size = {{ .FragmentSize }}
		include_length = yes
		auto_chain = yes
		check_crl = {{ .CheckCRL }}
		check_all_crl = {{ .CheckAllCRL }}
{{ if .CheckCRL }}
		ca_path = {{ .CertDir }}
		ca_path_reload_interval = {{ .CAPathReloadInterval }}
{{ end }}
		cipher_list = "DEFAULT"
		ecdh_curve = "prime256v1"
		tls_min_version = "{{ .TLSMinVersion }}"
		tls_max_version = "{{ .TLSMaxVersion }}"

		verify {
			skip_if_ocsp_ok = no
		}

		ocsp {
			enable = {{ .OCSPEnabled }}
			override_cert_url = {{ .OCSPOverrideCertURL }}
{{ if .OCSPURL }}
			url = "{{ .OCSPURL }}"
{{ end }}
			use_nonce = {{ .OCSPUseNonce }}
			timeout = {{ .OCSPTimeoutSeconds }}
			softfail = {{ .OCSPSoftFail }}
		}
	}

	peap {
		default_eap_type = {{ .PEAPInner }}
		tls = tls-common
		copy_request_to_tunnel = no
		use_tunneled_reply = no
		proxy_tunneled_request_as_eap = yes
		virtual_server = "inner-tunnel"
	}

	ttls {
		default_eap_type = {{ .TTLSInner }}
		tls = tls-common
		copy_request_to_tunnel = no
		use_tunneled_reply = no
		virtual_server = "inner-tunnel"
	}

	tls {
		tls = tls-common
		virtual_server = "inner-tunnel"
	}
{{ if .TEAPEnabled }}

	teap {
		default_eap_type = {{ .TEAPInner }}
		tls = tls-common
		copy_request_to_tunnel = no
		use_tunneled_reply = no
		virtual_server = "inner-tunnel"
	}
{{ end }}
{{ if .FASTEnabled }}

	fast {
		default_eap_type = {{ .FASTInner }}
		tls = tls-common
		copy_request_to_tunnel = no
		use_tunneled_reply = no
		virtual_server = "inner-tunnel"
	}
{{ end }}
{{ if .PWDEnabled }}

	pwd {
		group = {{ .PWDGroup }}
		server_id = "{{ .PWDServerID }}"
		fragment_size = {{ .PWDFragmentSize }}
	}
{{ end }}
{{ if .SIMEnabled }}

	sim {
		# EAP-SIM vectors are resolved by AegisNAS policy via {{ .SIMAKAVectorProvider }}.
	}
{{ end }}
{{ if .AKAEnabled }}

	aka {
		# EAP-AKA quintuplets are resolved by AegisNAS policy via {{ .SIMAKAVectorProvider }}.
	}
{{ end }}
{{ if .AKAPrimeEnabled }}

	aka_prime {
		# EAP-AKA-prime enforces network-name and KDF policy before enabling this block.
	}
{{ end }}

	mschapv2 {
		with_ntdomain_hack = no
		send_error = yes
	}
}
`
	data := struct {
		MaxSessions               int
		CertDir                   string
		DefaultType               string
		PEAPInner                 string
		TTLSInner                 string
		FrameworkStatus           string
		FrameworkMode             string
		FrameworkFailClosed       bool
		AllowedMethods            string
		AllowedInnerMethods       string
		TEAPEnabled               bool
		TEAPInner                 string
		TEAPChainMode             string
		TEAPRequireCryptoBinding  bool
		TEAPRequireChannelBinding bool
		FASTEnabled               bool
		FASTInner                 string
		FASTAllowPAC              bool
		FASTRequireCryptoBinding  bool
		PWDEnabled                bool
		PWDGroup                  int
		PWDServerID               string
		PWDPasswordSource         string
		PWDFragmentSize           int
		SIMAKAEnabled             bool
		SIMEnabled                bool
		AKAEnabled                bool
		AKAPrimeEnabled           bool
		SIMAKAMethods             string
		SIMAKAVectorProvider      string
		SIMAKARequireFreshVectors bool
		MethodTimeoutSeconds      int
		FragmentSize              int
		TLSMinVersion             string
		TLSMaxVersion             string
		CheckCRL                  string
		CheckAllCRL               string
		CAPathReloadInterval      int
		OCSPEnabled               string
		OCSPOverrideCertURL       string
		OCSPURL                   string
		OCSPUseNonce              string
		OCSPTimeoutSeconds        int
		OCSPSoftFail              string
	}{
		MaxSessions:               framework.EffectiveMaxSessions,
		CertDir:                   certDir,
		DefaultType:               framework.DefaultType,
		PEAPInner:                 framework.PEAPInner,
		TTLSInner:                 framework.TTLSInner,
		FrameworkStatus:           frameworkReport.Status,
		FrameworkMode:             framework.Mode,
		FrameworkFailClosed:       framework.FailClosed,
		AllowedMethods:            strings.Join(framework.AllowedMethods, ","),
		AllowedInnerMethods:       strings.Join(framework.AllowedInnerMethods, ","),
		TEAPEnabled:               teapPolicy.GeneratedInFreeRADIUS,
		TEAPInner:                 teapPolicy.DefaultInnerMethod,
		TEAPChainMode:             teapPolicy.ChainMode,
		TEAPRequireCryptoBinding:  teapPolicy.RequireCryptoBinding,
		TEAPRequireChannelBinding: teapPolicy.RequireChannelBinding,
		FASTEnabled:               fastPolicy.GeneratedInFreeRADIUS,
		FASTInner:                 fastPolicy.DefaultInnerMethod,
		FASTAllowPAC:              fastPolicy.AllowPAC,
		FASTRequireCryptoBinding:  fastPolicy.RequireCryptoBinding,
		PWDEnabled:                pwdPolicy.GeneratedInFreeRADIUS,
		PWDGroup:                  pwdPolicy.Group,
		PWDServerID:               radiusEscapeString(firstNonEmptyString(cfg.Radius.EAP.PWD.ServerID, "aegisnas-pwd")),
		PWDPasswordSource:         pwdPolicy.PasswordSource,
		PWDFragmentSize:           pwdPolicy.FragmentSize,
		SIMAKAEnabled:             simAKAPolicy.GeneratedInFreeRADIUS,
		SIMEnabled:                simAKAPolicy.GeneratedInFreeRADIUS && stringSliceContains(simAKAPolicy.GeneratedMethods, "sim"),
		AKAEnabled:                simAKAPolicy.GeneratedInFreeRADIUS && stringSliceContains(simAKAPolicy.GeneratedMethods, "aka"),
		AKAPrimeEnabled:           simAKAPolicy.GeneratedInFreeRADIUS && stringSliceContains(simAKAPolicy.GeneratedMethods, "aka-prime"),
		SIMAKAMethods:             eappkg.SIMAKAMethodSummary(simAKAPolicy.GeneratedMethods),
		SIMAKAVectorProvider:      simAKAPolicy.VectorProvider,
		SIMAKARequireFreshVectors: simAKAPolicy.RequireFreshVectors,
		MethodTimeoutSeconds:      framework.MethodTimeoutSeconds,
		FragmentSize:              framework.FragmentSize,
		TLSMinVersion:             cfg.Radius.EAP.TLSMinVersion,
		TLSMaxVersion:             cfg.Radius.EAP.TLSMaxVersion,
		CheckCRL:                  radiusYesNo(cfg.Radius.EAP.CheckCRL),
		CheckAllCRL:               radiusYesNo(cfg.Radius.EAP.CheckAllCRL),
		CAPathReloadInterval:      cfg.Radius.EAP.CAPathReloadInterval,
		OCSPEnabled:               radiusYesNo(cfg.Radius.EAP.OCSP.Enabled),
		OCSPOverrideCertURL:       radiusYesNo(cfg.Radius.EAP.OCSP.OverrideCertURL),
		OCSPURL:                   strings.TrimSpace(cfg.Radius.EAP.OCSP.URL),
		OCSPUseNonce:              radiusYesNo(cfg.Radius.EAP.OCSP.UseNonce),
		OCSPTimeoutSeconds:        cfg.Radius.EAP.OCSP.TimeoutSeconds,
		OCSPSoftFail:              radiusYesNo(cfg.Radius.EAP.OCSP.SoftFail),
	}
	var buf bytes.Buffer
	t := template.Must(template.New("eap").Parse(tmpl))
	err := t.Execute(&buf, data)
	return buf.String(), err
}

func radiusYesNo(value bool) string {
	if value {
		return "yes"
	}
	return "no"
}

func radiusEscapeString(value string) string {
	value = strings.TrimSpace(value)
	value = strings.ReplaceAll(value, `\`, `\\`)
	return strings.ReplaceAll(value, `"`, `\"`)
}

func firstNonEmptyString(values ...string) string {
	for _, value := range values {
		if strings.TrimSpace(value) != "" {
			return strings.TrimSpace(value)
		}
	}
	return ""
}

func stringSliceContains(values []string, target string) bool {
	for _, value := range values {
		if value == target {
			return true
		}
	}
	return false
}
