package radius

import (
	"bytes"
	"text/template"

	"github.com/yourorg/aegisnas-pi4/internal/config"
)

// GenerateEAPConfig creates the eap module configuration for FreeRADIUS.
func GenerateEAPConfig(cfg *config.Config, certDir string) (string, error) {
	tmpl := `# -*- text -*-
# eap.conf – generated by aegis-radius
eap {
	default_eap_type = {{ .DefaultType }}
	timer_expire = 60
	ignore_unknown_eap_types = no
	cisco_accounting_username_bug = no
	max_sessions = {{ .MaxSessions }}

	tls-config tls-common {
		private_key_file = {{ .CertDir }}/server.key
		certificate_file = {{ .CertDir }}/server.crt
		ca_file = {{ .CertDir }}/ca.crt
		dh_file = {{ .CertDir }}/dh
		random_file = /dev/urandom
		fragment_size = 1024
		include_length = yes
		auto_chain = yes
		check_crl = no
		cipher_list = "DEFAULT"
		ecdh_curve = "prime256v1"
		tls_min_version = "{{ .TLSMinVersion }}"
		tls_max_version = "{{ .TLSMaxVersion }}"
	}

	peap {
		default_eap_type = {{ .PEAPInner }}
		tls = tls-common
		copy_request_to_tunnel = no
		use_tunneled_reply = no
		proxy_tunneled_request_as_eap = yes
		virtual_server = "inner-tunnel"
	}

	ttls {
		default_eap_type = {{ .TTLSInner }}
		tls = tls-common
		copy_request_to_tunnel = no
		use_tunneled_reply = no
		virtual_server = "inner-tunnel"
	}

	tls {
		tls = tls-common
		virtual_server = "inner-tunnel"
	}

	mschapv2 {
		with_ntdomain_hack = no
		send_error = yes
	}
}
`
	data := struct {
		MaxSessions   int
		CertDir       string
		DefaultType   string
		PEAPInner     string
		TTLSInner     string
		TLSMinVersion string
		TLSMaxVersion string
	}{
		MaxSessions:   cfg.Radius.MaxSessions,
		CertDir:       certDir,
		DefaultType:   cfg.Radius.EAP.DefaultType,
		PEAPInner:     cfg.Radius.EAP.PEAPInner,
		TTLSInner:     cfg.Radius.EAP.TTLSInner,
		TLSMinVersion: cfg.Radius.EAP.TLSMinVersion,
		TLSMaxVersion: cfg.Radius.EAP.TLSMaxVersion,
	}
	var buf bytes.Buffer
	t := template.Must(template.New("eap").Parse(tmpl))
	err := t.Execute(&buf, data)
	return buf.String(), err
}
