package radius

import (
	"bytes"
	"fmt"
	"strings"
	"text/template"

	productconfigs "github.com/yourorg/aegisnas-pi4/configs"
	"github.com/yourorg/aegisnas-pi4/internal/config"
	"github.com/yourorg/aegisnas-pi4/internal/db"
)

// FreeRADIUSConfig bundles all generated configuration files.
type FreeRADIUSConfig struct {
	ClientsConf      string
	Dictionary       string
	VendorDictionary string
	EAPConf          string
	Users            string
	ModsLDAP         string
	ModsSQL          string
	ProxyConf        string
	SitesDefault     string
	SitesInnerTunnel string
}

const VendorDictionaryFilename = productconfigs.AegisNASVendorDictionaryFilename

// Generator creates FreeRADIUS configuration from the system config.
type Generator struct {
	cfg *config.Config
}

func NewGenerator(cfg *config.Config) *Generator {
	return &Generator{cfg: cfg}
}

// Generate produces all necessary FreeRADIUS configuration files.
func (g *Generator) Generate() (*FreeRADIUSConfig, error) {
	var out FreeRADIUSConfig
	var err error
	var clients []config.RadiusClient

	if db.DB != nil {
		clients, err = clientDefinitionsFromDB()
		if err != nil {
			if !isMissingRadiusClientsTable(err) {
				return nil, fmt.Errorf("clients generation: %w", err)
			}
			clients = append([]config.RadiusClient(nil), g.cfg.Radius.Clients...)
		}
	} else {
		clients = append([]config.RadiusClient(nil), g.cfg.Radius.Clients...)
	}
	clients = g.ensureBrokerClients(clients)
	out.ClientsConf, err = renderClientDefinitions(clients)
	if err != nil {
		return nil, fmt.Errorf("clients generation: %w", err)
	}

	out.Dictionary, err = g.renderDictionaryInclude()
	if err != nil {
		return nil, fmt.Errorf("dictionary generation: %w", err)
	}
	out.VendorDictionary, err = g.renderVendorDictionary()
	if err != nil {
		return nil, fmt.Errorf("vendor dictionary generation: %w", err)
	}

	// EAP configuration
	out.EAPConf, err = GenerateEAPConfig(g.cfg, g.cfg.Radius.CertDir)
	if err != nil {
		return nil, fmt.Errorf("eap generation: %w", err)
	}

	// Users file (static + dynamic users could be added later)
	out.Users, err = g.renderUsers()
	if err != nil {
		return nil, err
	}

	// LDAP module
	out.ModsLDAP, err = g.renderModsLDAP()
	if err != nil {
		return nil, err
	}

	// SQL module
	out.ModsSQL, err = g.renderModsSQL()
	if err != nil {
		return nil, err
	}

	// Upstream proxy configuration
	out.ProxyConf, err = g.renderProxyConf()
	if err != nil {
		return nil, err
	}

	// Sites
	out.SitesDefault, err = g.renderSitesDefault()
	if err != nil {
		return nil, err
	}
	out.SitesInnerTunnel, err = g.renderSitesInnerTunnel()
	if err != nil {
		return nil, err
	}

	return &out, nil
}

func clientDefinitionsFromDB() ([]config.RadiusClient, error) {
	rows, err := db.DB.Query(`SELECT shortname, ipaddr, secret, COALESCE(NULLIF(TRIM(nas_type), ''), 'other') FROM radius_clients WHERE enabled = 1`)
	if isMissingRadiusClientNASTypeColumn(err) {
		return legacyClientDefinitionsFromDB()
	}
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	var clients []config.RadiusClient
	for rows.Next() {
		var c config.RadiusClient
		if err := rows.Scan(&c.ShortName, &c.IP, &c.Secret, &c.NASType); err != nil {
			return nil, err
		}
		clients = append(clients, c)
	}
	return clients, rows.Err()
}

func legacyClientDefinitionsFromDB() ([]config.RadiusClient, error) {
	rows, err := db.DB.Query(`SELECT shortname, ipaddr, secret FROM radius_clients WHERE enabled = 1`)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	var clients []config.RadiusClient
	for rows.Next() {
		var c config.RadiusClient
		if err := rows.Scan(&c.ShortName, &c.IP, &c.Secret); err != nil {
			return nil, err
		}
		c.NASType = "other"
		clients = append(clients, c)
	}
	return clients, rows.Err()
}

func renderClientDefinitions(clients []config.RadiusClient) (string, error) {
	renderClients := make([]radiusClientDefinition, 0, len(clients))
	for _, client := range clients {
		renderClients = append(renderClients, radiusClientDefinition{
			IP:        client.IP,
			Secret:    client.Secret,
			ShortName: client.ShortName,
			NASType:   NormalizeClientNASType(client.NASType),
		})
	}

	tmpl := `# -*- text -*-
# clients.conf – generated by aegis-radius
{{- range .}}
client {{ .ShortName }} {
	ipaddr = {{ .IP }}
	secret = {{ .Secret }}
	shortname = {{ .ShortName }}
	nastype = {{ .NASType }}
}
{{- end}}
`
	var buf bytes.Buffer
	t := template.Must(template.New("clients").Parse(tmpl))
	err := t.Execute(&buf, renderClients)
	return buf.String(), err
}

type radiusClientDefinition struct {
	IP        string
	Secret    string
	ShortName string
	NASType   string
}

func (g *Generator) renderDictionaryInclude() (string, error) {
	return fmt.Sprintf(`# Local dictionary generated by aegis-radius.
# Product vendor attributes live in a separate AegisNAS dictionary file.
$INCLUDE %s
`, VendorDictionaryFilename), nil
}

func (g *Generator) renderVendorDictionary() (string, error) {
	if g.cfg == nil || !g.cfg.Radius.Vendor.Enabled {
		return "# AegisNAS product vendor dictionary generated by aegis-radius.\n# AegisNAS vendor attributes are disabled.\n", nil
	}
	identity := productconfigs.AegisNASVendorIdentity()
	idSource := identity.IDSource
	if g.cfg.Radius.Vendor.ID != identity.ID {
		idSource = "config:radius.vendor.id"
	}

	attrs := EffectiveVendorAttributes(g.cfg.Radius.Vendor)
	data := struct {
		VendorName  string
		VendorID    int
		IDSource    string
		Placeholder bool
		RegistryURL string
		ApplyURL    string
		InstallPath string
		IncludeLine string
		Attributes  []config.RadiusVendorAttribute
	}{
		VendorName:  strings.TrimSpace(g.cfg.Radius.Vendor.Name),
		VendorID:    g.cfg.Radius.Vendor.ID,
		IDSource:    idSource,
		Placeholder: g.cfg.Radius.Vendor.ID == productconfigs.AegisNASPlaceholderVendorID,
		RegistryURL: identity.RegistryURL,
		ApplyURL:    identity.ApplyURL,
		InstallPath: productconfigs.AegisNASVendorDictionaryInstallPath(ConfigDir()),
		IncludeLine: "$INCLUDE " + VendorDictionaryFilename,
		Attributes:  attrs,
	}
	tmpl := `# AegisNAS product vendor dictionary generated by aegis-radius.
# Install path: {{ .InstallPath }}
# Include from local FreeRADIUS dictionary with: {{ .IncludeLine }}
# Vendor ID source: {{ .IDSource }}
{{- if .Placeholder }}
# WARNING: 55555 is a lab placeholder. Request an IANA Private Enterprise Number before production VSA use.
# Registry: {{ .RegistryURL }}
# Apply: {{ .ApplyURL }}
{{- end }}
VENDOR {{ .VendorName }} {{ .VendorID }}

BEGIN-VENDOR {{ .VendorName }}
{{- range .Attributes }}
ATTRIBUTE {{ .Name }} {{ .Number }} {{ .Type }}
{{- end }}
END-VENDOR {{ .VendorName }}
`
	var buf bytes.Buffer
	t := template.Must(template.New("dictionary").Parse(tmpl))
	err := t.Execute(&buf, data)
	return buf.String(), err
}

func (g *Generator) renderUsers() (string, error) {
	// Users file is static for now; dynamic users handled by SQL/LDAP
	tmpl := `# users – local users (PAP)
# Generated by aegis-radius

DEFAULT	Group := "guest-basic", Fall-Through = Yes
`
	return tmpl, nil
}

func isMissingRadiusClientsTable(err error) bool {
	if err == nil {
		return false
	}
	return strings.Contains(strings.ToLower(err.Error()), "no such table: radius_clients")
}

func isMissingRadiusClientNASTypeColumn(err error) bool {
	if err == nil {
		return false
	}
	normalized := strings.ToLower(err.Error())
	return strings.Contains(normalized, "no such column") && strings.Contains(normalized, "nas_type")
}

func (g *Generator) ensureBrokerClients(existing []config.RadiusClient) []config.RadiusClient {
	clients := append([]config.RadiusClient(nil), existing...)
	ensure := func(ip, shortName string) {
		for i, client := range clients {
			if client.IP != ip {
				continue
			}
			clients[i].Secret = g.cfg.Radius.Secret
			if strings.TrimSpace(clients[i].ShortName) == "" {
				clients[i].ShortName = shortName
			}
			if strings.TrimSpace(clients[i].NASType) == "" {
				clients[i].NASType = "other"
			}
			return
		}
		clients = append(clients, config.RadiusClient{
			IP:        ip,
			Secret:    g.cfg.Radius.Secret,
			ShortName: shortName,
			NASType:   "other",
		})
	}

	ensure("127.0.0.1", "aegisnas-local-broker")
	ensure("::1", "aegisnas-local-broker-v6")
	return clients
}

func (g *Generator) renderModsLDAP() (string, error) {
	if !g.cfg.LDAP.Enabled {
		return "# LDAP disabled\n", nil
	}
	tmpl := `# mods-enabled/ldap
ldap {
	server = '{{ .LDAP.URL }}'
	port = 389
	identity = '{{ .LDAP.BindDN }}'
	password = '{{ .LDAP.BindPassword }}'
	base_dn = '{{ .LDAP.BaseDN }}'

	user {
		base_dn = "ou=users,${..base_dn}"
		filter = "{{ .LDAP.UserFilter }}"
	}
	group {
		base_dn = "ou=groups,${..base_dn}"
		membership_filter = "{{ .LDAP.GroupFilter }}"
	}
	options {
		chase_referrals = yes
		rebind = yes
		net_timeout = 5
	}
}
`
	var buf bytes.Buffer
	t := template.Must(template.New("ldap").Parse(tmpl))
	err := t.Execute(&buf, g.cfg)
	return buf.String(), err
}

func (g *Generator) renderModsSQL() (string, error) {
	tmpl := `# mods-enabled/sql
sql {
	dialect = "sqlite"
	driver = "rlm_sql_sqlite"
	sqlite {
		filename = "{{ .Database.Path }}"
		busy_timeout = 200
	}

	radius_db = "radius"

	accounting {
		reference = "%{tolower:type.%{Acct-Status-Type}}"
	}

	postauth {
		reference = ".query"
	}
}
`
	var buf bytes.Buffer
	t := template.Must(template.New("sql").Parse(tmpl))
	err := t.Execute(&buf, g.cfg)
	return buf.String(), err
}

func (g *Generator) renderProxyConf() (string, error) {
	if !g.cfg.Radius.Upstream.Enabled {
		return "# Upstream RADIUS proxy disabled\n", nil
	}

	type upstreamServer struct {
		Name     string
		Address  string
		AuthPort int
		AcctPort int
		Secret   string
	}

	servers := make([]upstreamServer, 0, len(g.cfg.Radius.Upstream.Servers))
	for _, server := range g.cfg.Radius.Upstream.Servers {
		authPort := server.AuthPort
		if authPort == 0 {
			authPort = g.cfg.Radius.AuthPort
		}
		acctPort := server.AcctPort
		if acctPort == 0 {
			acctPort = g.cfg.Radius.AcctPort
		}
		servers = append(servers, upstreamServer{
			Name:     server.Name,
			Address:  server.Address,
			AuthPort: authPort,
			AcctPort: acctPort,
			Secret:   server.Secret,
		})
	}

	data := struct {
		Upstream config.RadiusUpstreamConfig
		PoolName string
		Servers  []upstreamServer
	}{
		Upstream: g.cfg.Radius.Upstream,
		PoolName: "aegis_upstream_pool",
		Servers:  servers,
	}

	tmpl := `# proxy.conf - generated by aegis-radius
# Upstream AAA proxy mode is enabled. Access-Request and Accounting-Request
# packets are forwarded to the configured home server pool.
proxy server {
	default_fallback = no
}

{{- range .Servers }}
home_server {{ .Name }} {
	type = auth+acct
	ipaddr = {{ .Address }}
	port = {{ .AuthPort }}
	acctport = {{ .AcctPort }}
	secret = {{ .Secret }}
	response_window = {{ $.Upstream.ResponseWindow }}
	zombie_period = {{ $.Upstream.ZombiePeriod }}
	{{- if eq $.Upstream.StatusCheck "status-server" }}
	status_check = status-server
	check_interval = {{ $.Upstream.CheckInterval }}
	num_answers_to_alive = {{ $.Upstream.NumAnswersToAlive }}
	{{- else }}
	status_check = none
	revive_interval = {{ $.Upstream.ReviveInterval }}
	{{- end }}
}

{{- end }}
home_server_pool {{ .PoolName }} {
	type = {{ .Upstream.PoolStrategy }}
{{- range .Servers }}
	home_server = {{ .Name }}
{{- end }}
}

realm {{ .Upstream.Realm }} {
	pool = {{ .PoolName }}
	{{- if .Upstream.StripRealm }}
	strip
	{{- else }}
	nostrip
	{{- end }}
}
`
	var buf bytes.Buffer
	t := template.Must(template.New("proxy").Parse(tmpl))
	err := t.Execute(&buf, data)
	return buf.String(), err
}

func (g *Generator) renderSitesDefault() (string, error) {
	tmpl := `# sites-enabled/default
server default {
	listen {
		type = auth
		ipaddr = *
		port = {{ .Radius.AuthPort }}
	}
	listen {
		type = acct
		ipaddr = *
		port = {{ .Radius.AcctPort }}
	}

	authorize {
		preprocess
		chap
		mschap
		digest
		suffix
		{{- if .Radius.Upstream.Enabled }}
		update control {
			Proxy-To-Realm := "{{ .Radius.Upstream.Realm }}"
		}
		{{- else }}
		eap {
			ok = return
		}
		files
		{{- if .LDAP.Enabled }}
		ldap
		{{- end }}
		pap
		{{- end }}
	}

	authenticate {
		Auth-Type PAP {
			pap
		}
		Auth-Type CHAP {
			chap
		}
		Auth-Type MS-CHAP {
			mschap
		}
		eap
	}

	preacct {
		preprocess
		acct_unique
		suffix
		files
		{{- if .Radius.Upstream.Enabled }}
		update control {
			Proxy-To-Realm := "{{ .Radius.Upstream.Realm }}"
		}
		{{- end }}
	}

	accounting {
		detail
		unix
		sql
		exec
	}

	session {
		radutmp
	}

	post-auth {
		exec
		reply_log
	}
}
`
	var buf bytes.Buffer
	t := template.Must(template.New("default").Parse(tmpl))
	err := t.Execute(&buf, g.cfg)
	return buf.String(), err
}

func (g *Generator) renderSitesInnerTunnel() (string, error) {
	tmpl := `# sites-enabled/inner-tunnel
server inner-tunnel {
	listen {
		ipaddr = 127.0.0.1
		port = 18120
		type = auth
	}

	authorize {
		filter_username
		preprocess
		chap
		mschap
		suffix
		{{- if .Radius.Upstream.Enabled }}
		update control {
			Proxy-To-Realm := "{{ .Radius.Upstream.Realm }}"
		}
		{{- else }}
		update control {
			&Proxy-To-Realm := LOCAL
		}
		eap {
			ok = return
		}
		files
		{{- if .LDAP.Enabled }}
		ldap
		{{- end }}
		pap
		{{- end }}
	}

	authenticate {
		Auth-Type PAP {
			pap
		}
		Auth-Type CHAP {
			chap
		}
		Auth-Type MS-CHAP {
			mschap
		}
		eap
	}

	session {
		radutmp
	}

	post-auth {
		Post-Auth-Type REJECT {
			attr_filter.access_reject
		}
	}
}
`
	var buf bytes.Buffer
	t := template.Must(template.New("inner-tunnel").Parse(tmpl))
	err := t.Execute(&buf, g.cfg)
	return buf.String(), err
}
